-- ===============================================================================================
--  GURUKUL OS - COMPLETE DATABASE SCHEMA (v25.2.0)
--  Generated by: Antigravity AI
--  Date: January 26, 2026
--  Description: Full schema reset including all missing modules (Transport, Tasks, Departments, etc.)
--               Fixed "relation does not exist" error by removing redundant trigger drops.
-- ===============================================================================================

BEGIN;

-- 1. CLEANUP PROTOCOL (DROP EVERYTHING CAREFULLY)
-- ===============================================================================================

-- Drop Functions first (CASCADE handles dependencies)
DROP FUNCTION IF EXISTS public.trigger_on_student_placement() CASCADE;
DROP FUNCTION IF EXISTS public.generate_student_ledger_for_student(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.admin_generate_bulk_invoices(BIGINT, BIGINT, TEXT, TEXT, DATE) CASCADE;
DROP FUNCTION IF EXISTS public.admin_sync_student_billing(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.admin_reconcile_student_account(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.get_student_running_ledger(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.get_student_financial_node(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.get_student_financial_nodes(BIGINT) CASCADE;
DROP FUNCTION IF EXISTS public.check_is_admin() CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.get_my_children_profiles() CASCADE;
DROP FUNCTION IF EXISTS public.get_my_children_profiles(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.parent_initialize_vault_slots_all() CASCADE;
DROP FUNCTION IF EXISTS public.parent_get_document_requirements(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.parent_complete_document_upload(BIGINT, UUID, TEXT, TEXT, BIGINT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_finalize_enrollment(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.get_admissions_v2(BIGINT) CASCADE;
DROP FUNCTION IF EXISTS public.parent_switch_student_view(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.get_student_dashboard_data(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.switch_active_role(TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.upsert_teacher_profile(UUID, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, INT, DATE) CASCADE;
DROP FUNCTION IF EXISTS public.generate_admission_share_code(UUID, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.revoke_my_share_code(BIGINT) CASCADE;
DROP FUNCTION IF EXISTS public.initialize_school_admin() CASCADE;
DROP FUNCTION IF EXISTS public.create_school_branch(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN, TEXT, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.update_school_branch(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN, TEXT, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.delete_school_branch(BIGINT) CASCADE;
DROP FUNCTION IF EXISTS public.complete_branch_step() CASCADE;
DROP FUNCTION IF EXISTS public.verify_and_link_branch_admin(TEXT) CASCADE;

-- Drop Tables (Order matters: Child tables first, or just use CASCADE)
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.communications CASCADE;
DROP TABLE IF EXISTS public.tasks CASCADE;
DROP TABLE IF EXISTS public.lesson_plans CASCADE;
DROP TABLE IF EXISTS public.workshops CASCADE;
DROP TABLE IF EXISTS public.bus_attendance CASCADE;
DROP TABLE IF EXISTS public.bus_routes CASCADE;
DROP TABLE IF EXISTS public.transport_profiles CASCADE;
DROP TABLE IF EXISTS public.expense_documents CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.student_fee_accounts CASCADE;
DROP TABLE IF EXISTS public.fee_payments CASCADE;
DROP TABLE IF EXISTS public.fee_invoices CASCADE;
DROP TABLE IF EXISTS public.student_fee_assignments CASCADE;
DROP TABLE IF EXISTS public.fee_components CASCADE;
DROP TABLE IF EXISTS public.fee_structures CASCADE;
DROP TABLE IF EXISTS public.submissions CASCADE;
DROP TABLE IF EXISTS public.assignments CASCADE;
DROP TABLE IF EXISTS public.attendance_records CASCADE;
DROP TABLE IF EXISTS public.timetables CASCADE;
DROP TABLE IF EXISTS public.study_materials CASCADE;
DROP TABLE IF EXISTS public.course_modules CASCADE;
DROP TABLE IF EXISTS public.courses CASCADE;
DROP TABLE IF EXISTS public.school_departments CASCADE;
DROP TABLE IF EXISTS public.document_requirements CASCADE;
DROP TABLE IF EXISTS public.admission_documents CASCADE;
DROP TABLE IF EXISTS public.share_codes CASCADE;
DROP TABLE IF EXISTS public.enquiries CASCADE;
DROP TABLE IF EXISTS public.admissions CASCADE;
DROP TABLE IF EXISTS public.student_profiles CASCADE;
DROP TABLE IF EXISTS public.teacher_profiles CASCADE;
DROP TABLE IF EXISTS public.parent_profiles CASCADE;
DROP TABLE IF EXISTS public.school_admin_profiles CASCADE;
DROP TABLE IF EXISTS public.staff_profiles CASCADE;
DROP TABLE IF EXISTS public.ecommerce_profiles CASCADE;
DROP TABLE IF EXISTS public.store_products CASCADE;
DROP TABLE IF EXISTS public.store_orders CASCADE;
DROP TABLE IF EXISTS public.school_classes CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.school_branches CASCADE;

-- 2. EXTENSIONS
-- ===============================================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 3. CORE TABLES & IDENTITIES
-- ===============================================================================================

CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    display_name TEXT,
    role TEXT DEFAULT 'Student',
    phone TEXT,
    branch_id BIGINT,
    profile_photo_url TEXT,
    is_active BOOLEAN DEFAULT true,
    profile_completed BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.school_admin_profiles (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
    school_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    admin_contact_name TEXT,
    admin_contact_phone TEXT,
    onboarding_step TEXT DEFAULT 'pending'
);

CREATE TABLE public.school_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    is_main_branch BOOLEAN DEFAULT false,
    admin_email TEXT,
    access_key TEXT UNIQUE,
    school_id UUID REFERENCES public.school_admin_profiles(user_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'Active',
    base_currency TEXT DEFAULT 'INR'
);

ALTER TABLE public.profiles ADD CONSTRAINT fk_profiles_branch FOREIGN KEY (branch_id) REFERENCES public.school_branches(id);

CREATE TABLE public.school_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    hod_id UUID REFERENCES public.profiles(id),
    branch_id BIGINT REFERENCES public.school_branches(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.school_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    grade_level TEXT,
    section TEXT,
    academic_year TEXT,
    class_teacher_id UUID REFERENCES public.profiles(id),
    branch_id BIGINT REFERENCES public.school_branches(id),
    capacity INT DEFAULT 40,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Specialized Profiles
CREATE TABLE public.student_profiles (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
    grade TEXT,
    assigned_class_id BIGINT REFERENCES public.school_classes(id),
    roll_number TEXT,
    student_id_number TEXT,
    parent_guardian_details TEXT,
    date_of_birth DATE,
    gender TEXT,
    address TEXT,
    enrollment_status TEXT DEFAULT 'Enrolled',
    branch_id BIGINT REFERENCES public.school_branches(id),
    emergency_contact TEXT,
    medical_info TEXT
);

CREATE TABLE public.teacher_profiles (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
    subject_specialization TEXT,
    qualification TEXT,
    experience_years INT,
    bio TEXT,
    designation TEXT,
    department_id BIGINT REFERENCES public.school_departments(id),
    workload_limit INT DEFAULT 30,
    joining_date DATE
);

CREATE TABLE public.parent_profiles (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
    relationship_to_student TEXT,
    gender TEXT,
    number_of_children INT DEFAULT 1,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    pin_code TEXT
);
 
 -- Ecommerce Module
 CREATE TABLE public.ecommerce_profiles (
     user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
     store_name TEXT,
     business_type TEXT
 );
 
 CREATE TABLE public.store_products (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name TEXT NOT NULL,
     description TEXT,
     price NUMERIC NOT NULL,
     stock_quantity INT DEFAULT 0,
     category TEXT,
     image_url TEXT,
     branch_id BIGINT REFERENCES public.school_branches(id),
     created_at TIMESTAMPTZ DEFAULT NOW()
 );
 
 CREATE TABLE public.store_orders (
     id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
     student_id UUID REFERENCES public.profiles(id),
     total_amount NUMERIC NOT NULL,
     status TEXT DEFAULT 'Pending', -- 'Pending', 'Completed', 'Cancelled'
     created_at TIMESTAMPTZ DEFAULT NOW()
 );
 
 ALTER TABLE public.ecommerce_profiles ENABLE ROW LEVEL SECURITY;
 ALTER TABLE public.store_products ENABLE ROW LEVEL SECURITY;
 ALTER TABLE public.store_orders ENABLE ROW LEVEL SECURITY;
 
 CREATE POLICY "Users view own ecommerce profile" ON public.ecommerce_profiles FOR ALL USING (user_id = auth.uid());
 CREATE POLICY "Public view active products" ON public.store_products FOR SELECT USING (true);
 CREATE POLICY "Operators manage products" ON public.store_products FOR ALL USING (
     EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'Ecommerce Operator')
 );
 CREATE POLICY "Users manage own orders" ON public.store_orders FOR ALL USING (student_id = auth.uid());
 
 CREATE TABLE public.transport_profiles (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
    license_number TEXT,
    vehicle_details TEXT,
    route_id BIGINT 
);

-- moved up to resolve dependency

CREATE TABLE public.staff_profiles (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
    designation TEXT,
    department TEXT,
    joining_date DATE
);

CREATE TABLE public.notifications (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    title TEXT NOT NULL,
    message TEXT,
    type TEXT DEFAULT 'info', -- 'info', 'warning', 'success', 'error'
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ADMISSIONS & CRM
-- ===============================================================================================

CREATE TABLE public.admissions (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    applicant_name TEXT NOT NULL,
    grade TEXT,
    status TEXT DEFAULT 'Pending Review', 
    parent_name TEXT,
    parent_email TEXT,
    parent_phone TEXT,
    parent_id UUID REFERENCES public.profiles(id),
    student_user_id UUID REFERENCES public.profiles(id),
    branch_id BIGINT REFERENCES public.school_branches(id),
    date_of_birth DATE,
    gender TEXT,
    emergency_contact TEXT,
    medical_info TEXT,
    profile_photo_url TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.enquiries (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    applicant_name TEXT,
    parent_name TEXT,
    parent_email TEXT,
    parent_phone TEXT,
    grade TEXT,
    status TEXT DEFAULT 'ENQUIRY_ACTIVE',
    notes TEXT,
    branch_id BIGINT REFERENCES public.school_branches(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.share_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    admission_id UUID REFERENCES public.admissions(id),
    status TEXT DEFAULT 'Active', -- 'Active', 'Expired', 'Revoked', 'Redeemed'
    code_type TEXT DEFAULT 'Enquiry', -- 'Enquiry' or 'Admission'
    purpose TEXT,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES public.profiles(id)
);

CREATE TABLE public.document_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id UUID REFERENCES public.admissions(id),
    document_name TEXT NOT NULL,
    is_mandatory BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'Pending'
);

CREATE TABLE public.admission_documents (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    admission_id UUID REFERENCES public.admissions(id) ON DELETE CASCADE,
    document_name TEXT NOT NULL,
    file_name TEXT,
    storage_path TEXT,
    file_size BIGINT,
    mime_type TEXT,
    status TEXT DEFAULT 'Pending',
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ACADEMIC & LMS
-- ===============================================================================================

CREATE TABLE public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    code TEXT,
    description TEXT,
    grade_level TEXT,
    teacher_id UUID REFERENCES public.profiles(id),
    branch_id BIGINT REFERENCES public.school_branches(id),
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.course_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    order_index INT DEFAULT 0,
    content TEXT
);

CREATE TABLE public.timetables (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    class_id BIGINT REFERENCES public.school_classes(id),
    teacher_id UUID REFERENCES public.profiles(id),
    subject TEXT,
    day_of_week TEXT,
    start_time TIME,
    end_time TIME,
    room_number TEXT,
    branch_id BIGINT REFERENCES public.school_branches(id)
);

CREATE TABLE public.assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    course_id BIGINT REFERENCES public.courses(id),
    class_id BIGINT REFERENCES public.school_classes(id),
    teacher_id UUID REFERENCES public.profiles(id),
    due_date TIMESTAMPTZ,
    file_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT REFERENCES public.assignments(id),
    student_id UUID REFERENCES public.profiles(id),
    file_path TEXT,
    grade TEXT,
    feedback TEXT,
    status TEXT DEFAULT 'Submitted',
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.study_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    subject TEXT,
    class_id BIGINT REFERENCES public.school_classes(id),
    file_path TEXT,
    uploaded_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.profiles(id),
    class_id BIGINT REFERENCES public.school_classes(id),
    date DATE DEFAULT CURRENT_DATE,
    status TEXT CHECK (status IN ('Present', 'Absent', 'Late')),
    recorded_by UUID REFERENCES public.profiles(id),
    notes TEXT
);

CREATE TABLE public.lesson_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id UUID REFERENCES public.profiles(id),
    class_id BIGINT REFERENCES public.school_classes(id),
    subject TEXT,
    lesson_date DATE,
    objectives TEXT,
    activities TEXT,
    resources TEXT
);

CREATE TABLE public.workshops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    date DATE,
    organizer UUID REFERENCES public.profiles(id)
);

-- 6. TRANSPORT & LOGISTICS
-- ===============================================================================================

CREATE TABLE public.bus_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    driver_id UUID REFERENCES public.profiles(id),
    vehicle_number TEXT,
    capacity INT,
    branch_id BIGINT REFERENCES public.school_branches(id)
);

CREATE TABLE public.bus_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT REFERENCES public.bus_routes(id),
    student_id UUID REFERENCES public.profiles(id),
    date DATE DEFAULT CURRENT_DATE,
    status TEXT, -- 'Boarded', 'Absent'
    trip_type TEXT -- 'Pickup', 'Drop'
);

-- 7. OPERATIONS & TASKS
-- ===============================================================================================

CREATE TABLE public.tasks (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    assigned_to UUID REFERENCES public.profiles(id),
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT DEFAULT 'MEDIUM',
    status TEXT DEFAULT 'Todo', -- 'Todo', 'In Progress', 'Completed'
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. FINANCE ENGINE
-- ===============================================================================================

CREATE TABLE public.fee_structures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    target_grade TEXT,
    academic_year TEXT,
    currency TEXT DEFAULT 'INR',
    status TEXT DEFAULT 'Active',
    is_default BOOLEAN DEFAULT false,
    branch_id BIGINT REFERENCES public.school_branches(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.fee_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id BIGINT REFERENCES public.fee_structures(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    amount NUMERIC DEFAULT 0,
    frequency TEXT
);

CREATE TABLE public.student_fee_assignments (
    student_id UUID REFERENCES public.profiles(id) PRIMARY KEY,
    structure_id BIGINT REFERENCES public.fee_structures(id),
    assigned_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.fee_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.profiles(id),
    amount NUMERIC NOT NULL,
    due_date DATE,
    description TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.fee_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.profiles(id),
    invoice_id BIGINT REFERENCES public.fee_invoices(id),
    amount NUMERIC NOT NULL,
    payment_date TIMESTAMPTZ DEFAULT NOW(),
    payment_method TEXT,
    transaction_id TEXT,
    status TEXT DEFAULT 'Completed',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.student_fee_accounts (
    student_id UUID REFERENCES public.profiles(id) PRIMARY KEY,
    total_billed NUMERIC DEFAULT 0,
    total_paid NUMERIC DEFAULT 0,
    outstanding_balance NUMERIC DEFAULT 0,
    integrity_score INT DEFAULT 100,
    unallocated_funds NUMERIC DEFAULT 0,
    last_synced_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT,
    description TEXT,
    amount NUMERIC,
    vendor_name TEXT,
    expense_date DATE,
    status TEXT DEFAULT 'Pending',
    branch_id BIGINT REFERENCES public.school_branches(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.expense_documents (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    expense_id BIGINT REFERENCES public.expenses(id) ON DELETE CASCADE,
    file_path TEXT,
    file_name TEXT,
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. COMMUNICATIONS
-- ===============================================================================================

CREATE TABLE public.communications (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    subject TEXT,
    body TEXT,
    sender_id UUID REFERENCES public.profiles(id),
    recipients TEXT[], -- Storing arrays of IDs/Roles for simple broadcasting
    target_criteria JSONB,
    sent_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id),
    action TEXT,
    details JSONB,
    ip_address TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 10. ROW LEVEL SECURITY (RLS)
-- ===============================================================================================
-- Enable RLS on valid tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timetables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_admin_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transport_profiles ENABLE ROW LEVEL SECURITY;

-- HELPER: Anti-Recursion Function
CREATE OR REPLACE FUNCTION public.check_is_admin()
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    -- This runs as the function creator (postgres), bypassing RLS
    RETURN EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() 
        AND role IN ('Super Admin', 'School Admin', 'Branch Admin')
    );
END;
$$;

-- Basic Policies
-- Allow users to insert their own profile (Critical for self-healing)
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Allow users to update their own profile (Critical for role selection)
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
-- Note: 'Public' policy limited to SELECT to prevent unauthorized edits.
CREATE POLICY "Public profiles are viewable by authenticated" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
-- Admin policy uses the secure helper
CREATE POLICY "Admins have full access" ON public.profiles FOR ALL USING (public.check_is_admin());

-- Generic Policies for Sub-Profiles
CREATE POLICY "Users view own school admin profile" ON public.school_admin_profiles FOR ALL USING (user_id = auth.uid());
CREATE POLICY "Users view own staff profile" ON public.staff_profiles FOR ALL USING (user_id = auth.uid());
CREATE POLICY "Users view own notifications" ON public.notifications FOR ALL USING (user_id = auth.uid());
CREATE POLICY "Users view own transport profile" ON public.transport_profiles FOR ALL USING (user_id = auth.uid());
CREATE POLICY "Users manage own parent profile" ON public.parent_profiles FOR ALL USING (user_id = auth.uid());

-- RLS: Share Code Management
ALTER TABLE public.share_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Parents manage own share codes" ON public.share_codes
    FOR ALL USING (
        created_by = auth.uid()
        OR EXISTS (
            SELECT 1 FROM public.admissions aa 
            WHERE aa.id = share_codes.admission_id 
            AND (aa.parent_id = auth.uid() OR aa.parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid()))
        )
    );

-- 11. RPC FUNCTIONS
-- ===============================================================================================

-- Helper: Reconcile Student Account
CREATE OR REPLACE FUNCTION public.admin_reconcile_student_account(p_student_id UUID)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_total_billed NUMERIC;
    v_total_paid NUMERIC;
    v_unallocated NUMERIC;
    v_integrity INT;
BEGIN
    SELECT COALESCE(SUM(amount), 0) INTO v_total_billed 
    FROM public.fee_invoices 
    WHERE student_id = p_student_id AND status != 'Cancelled';

    SELECT COALESCE(SUM(amount), 0) INTO v_total_paid 
    FROM public.fee_payments 
    WHERE student_id = p_student_id AND status IN ('Completed', 'Pending');

    SELECT COALESCE(SUM(amount), 0) INTO v_unallocated
    FROM public.fee_payments
    WHERE student_id = p_student_id AND invoice_id IS NULL AND status = 'Completed';

    v_integrity := CASE 
        WHEN v_total_billed <= 0 AND v_total_paid > 0 THEN 100
        WHEN v_total_billed <= 0 THEN 100
        ELSE GREATEST(0, LEAST(100, (v_total_paid / v_total_billed * 100)::INT))
    END;

    INSERT INTO public.student_fee_accounts (
        student_id, total_billed, total_paid, outstanding_balance, 
        integrity_score, last_synced_at, unallocated_funds
    )
    VALUES (
        p_student_id, v_total_billed, v_total_paid, (v_total_billed - v_total_paid), 
        v_integrity, NOW(), v_unallocated
    )
    ON CONFLICT (student_id) DO UPDATE SET
        total_billed = EXCLUDED.total_billed,
        total_paid = EXCLUDED.total_paid,
        outstanding_balance = EXCLUDED.outstanding_balance,
        integrity_score = EXCLUDED.integrity_score,
        unallocated_funds = EXCLUDED.unallocated_funds,
        last_synced_at = NOW();
END;
$$;

-- Helper: Generate Ledger (Auto-Invoice)
CREATE OR REPLACE FUNCTION public.generate_student_ledger_for_student(p_student_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_grade TEXT;
    v_structure_id BIGINT;
    v_component RECORD;
    v_count INT := 0;
BEGIN
    SELECT grade INTO v_grade FROM public.student_profiles WHERE user_id = p_student_id;
    IF v_grade IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Grade context not initialized.');
    END IF;

    SELECT id INTO v_structure_id 
    FROM public.fee_structures 
    WHERE target_grade = v_grade AND status = 'Active' AND is_default = true
    ORDER BY created_at DESC LIMIT 1;

    IF v_structure_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'No default active structure for Grade ' || v_grade);
    END IF;

    INSERT INTO public.student_fee_assignments (student_id, structure_id)
    VALUES (p_student_id, v_structure_id)
    ON CONFLICT (student_id) DO UPDATE SET structure_id = v_structure_id;

    FOR v_component IN 
        SELECT * FROM public.fee_components WHERE structure_id = v_structure_id
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM public.fee_invoices 
            WHERE student_id = p_student_id 
            AND description ILIKE v_component.name || '%'
            AND status != 'Cancelled'
        ) THEN
            INSERT INTO public.fee_invoices (
                student_id, amount, due_date, description, status, created_at
            ) VALUES (
                p_student_id, v_component.amount, NOW() + INTERVAL '15 days',
                v_component.name || ' (INITIAL_SYNC)', 'Pending', NOW()
            );
            v_count := v_count + 1;
        END IF;
    END LOOP;

    PERFORM public.admin_reconcile_student_account(p_student_id);

    RETURN jsonb_build_object('success', true, 'invoices_created', v_count, 'structure_id', v_structure_id);
END;
$$;

-- Trigger: On Student Placement
CREATE OR REPLACE FUNCTION public.trigger_on_student_placement()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'UPDATE') AND 
       (COALESCE(NEW.grade, '') <> COALESCE(OLD.grade, '') OR 
        COALESCE(NEW.assigned_class_id, 0) <> COALESCE(OLD.assigned_class_id, 0)) THEN
        PERFORM public.generate_student_ledger_for_student(NEW.user_id);
    END IF;
    IF (TG_OP = 'INSERT') AND NEW.grade IS NOT NULL THEN
        PERFORM public.generate_student_ledger_for_student(NEW.user_id);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_on_student_placement
    AFTER INSERT OR UPDATE OF grade, assigned_class_id ON public.student_profiles
    FOR EACH ROW EXECUTE FUNCTION public.trigger_on_student_placement();

-- 12. STORAGE BUCKETS (Simulated)
-- ===============================================================================================
DO $$
BEGIN
    INSERT INTO storage.buckets (id, name, public) VALUES ('profiles', 'profiles', true) ON CONFLICT (id) DO NOTHING;
    INSERT INTO storage.buckets (id, name, public) VALUES ('documents', 'documents', false) ON CONFLICT (id) DO NOTHING;
    INSERT INTO storage.buckets (id, name, public) VALUES ('assignments', 'assignments', false) ON CONFLICT (id) DO NOTHING;
    INSERT INTO storage.buckets (id, name, public) VALUES ('receipts', 'receipts', false) ON CONFLICT (id) DO NOTHING;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Storage setup skipped or failed.';
END $$;

-- 13. AUTH IDENTITY HANDSHAKE
-- ===============================================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, display_name, role)
    VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'full_name', NULL);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for Auth
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 14. PARENT & STUDENT ACCESS RPCs
-- ===============================================================================================

-- RPC: Get My Children Profiles (For Parents)
-- Logic: Finds admission applications linked to this parent (by email or phone usually, but here we might need a simpler link for now).
-- Since we don't have a reliable email link in the admissions table for 'parent_user_id' yet, we'll rely on a direct link or fallback to email matching (weak link) or a junction table. for now, let's assume 'parent_email' matches 'email' in profiles.
-- BETTER: We should rely on `admissions` having a `parent_id` if we want strict linking.
-- FOR NOW: We will use the `parent_email` from `admissions` matching the `email` of the logged-in parent.

DROP FUNCTION IF EXISTS public.get_my_children_profiles() CASCADE;
CREATE OR REPLACE FUNCTION public.get_my_children_profiles()
RETURNS TABLE (
    id UUID,
    applicant_name TEXT,
    grade TEXT,
    status TEXT,
    profile_photo_url TEXT,
    date_of_birth DATE,
    gender TEXT,
    medical_info TEXT,
    emergency_contact TEXT,
    student_user_id UUID,
    parent_email TEXT
) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY
    SELECT 
        a.id,
        a.applicant_name,
        a.grade,
        a.status,
        a.profile_photo_url,
        a.date_of_birth,
        a.gender,
        a.medical_info,
        a.emergency_contact,
        a.student_user_id,
        a.parent_email
    FROM public.admissions a
    WHERE a.parent_id = auth.uid()
       OR a.parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid())
    ORDER BY a.submitted_at DESC;
END;
$$;

-- RPC: Artifact Vault Synchronization Logic
DROP FUNCTION IF EXISTS public.parent_initialize_vault_slots_all() CASCADE;
CREATE OR REPLACE FUNCTION public.parent_initialize_vault_slots_all()
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_admission RECORD;
    v_doc_name TEXT;
    v_mandatory_docs TEXT[] := ARRAY['Birth Certificate', 'Identity Proof', 'Medical Report', 'Previous Transcript'];
BEGIN
    FOR v_admission IN 
        SELECT id FROM public.admissions 
        WHERE parent_id = auth.uid() 
           OR parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid()) 
    LOOP
        FOR v_doc_name IN SELECT unnest(v_mandatory_docs) LOOP
            IF NOT EXISTS (SELECT 1 FROM public.document_requirements WHERE admission_id = v_admission.id AND document_name = v_doc_name) THEN
                INSERT INTO public.document_requirements (admission_id, document_name, is_mandatory, status)
                VALUES (v_admission.id, v_doc_name, true, 'Pending');
            END IF;
        END LOOP;
    END LOOP;
END;
$$;

DROP FUNCTION IF EXISTS public.parent_get_document_requirements(UUID) CASCADE;
CREATE OR REPLACE FUNCTION public.parent_get_document_requirements(p_user_id UUID)
RETURNS SETOF JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY
    SELECT row_to_json(r)::jsonb
    FROM (
        SELECT 
            dr.*,
            (
                SELECT jsonb_agg(ad)
                FROM (
                    SELECT * FROM public.admission_documents 
                    WHERE admission_id = dr.admission_id 
                    AND document_name = dr.document_name
                    ORDER BY uploaded_at DESC
                ) ad
            ) as admission_documents
        FROM public.document_requirements dr
        JOIN public.admissions a ON dr.admission_id = a.id
        WHERE a.parent_id = p_user_id 
           OR a.parent_email = (SELECT email FROM public.profiles WHERE profiles.id = p_user_id)
    ) r;
END;
$$;

DROP FUNCTION IF EXISTS public.parent_complete_document_upload(BIGINT, UUID, TEXT, TEXT, BIGINT, TEXT) CASCADE;
CREATE OR REPLACE FUNCTION public.parent_complete_document_upload(
    p_requirement_id BIGINT,
    p_admission_id UUID,
    p_file_name TEXT,
    p_storage_path TEXT,
    p_file_size BIGINT,
    p_mime_type TEXT
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    -- Insert doc record
    INSERT INTO public.admission_documents (
        admission_id, 
        document_name, 
        file_name,
        storage_path, 
        file_size,
        mime_type,
        status
    ) 
    SELECT 
        p_admission_id, 
        document_name, 
        p_file_name,
        p_storage_path, 
        p_file_size,
        p_mime_type,
        'Submitted'
    FROM public.document_requirements 
    WHERE id = p_requirement_id;

    -- Update requirement status
    UPDATE public.document_requirements 
    SET status = 'Submitted' 
    WHERE id = p_requirement_id;
END;
$$;

-- RPC: Generate Admission Share Code
DROP FUNCTION IF EXISTS public.generate_admission_share_code(UUID, TEXT, TEXT) CASCADE;

CREATE OR REPLACE FUNCTION public.generate_admission_share_code(
    p_admission_id UUID,
    p_code_type TEXT,
    p_purpose TEXT
) RETURNS TEXT LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_code TEXT;
    v_parent_id UUID;
BEGIN
    -- Ownership Check
    SELECT parent_id INTO v_parent_id FROM public.admissions WHERE id = p_admission_id;
    
    IF v_parent_id IS NULL OR v_parent_id <> auth.uid() THEN
        -- Check if current user is the parent via email fallback
        IF NOT EXISTS (
            SELECT 1 FROM public.admissions a
            JOIN public.profiles p ON p.email = a.parent_email
            WHERE a.id = p_admission_id AND p.id = auth.uid()
        ) THEN
            RAISE EXCEPTION 'Access Denied: Node ownership verification failed.';
        END IF;
    END IF;

    -- Generate random 6-char alphanumeric code
    v_code := upper(substr(md5(random()::text), 1, 6));

    INSERT INTO public.share_codes (
        code, 
        admission_id, 
        code_type, 
        purpose, 
        expires_at, 
        created_by
    ) VALUES (
        v_code, 
        p_admission_id, 
        p_code_type, 
        p_purpose, 
        NOW() + INTERVAL '24 hours',
        auth.uid()
    );

    RETURN v_code;
END;
$$;

-- RPC: Revoke My Share Code
DROP FUNCTION IF EXISTS public.revoke_my_share_code(BIGINT) CASCADE;

CREATE OR REPLACE FUNCTION public.revoke_my_share_code(p_code_id BIGINT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    UPDATE public.share_codes 
    SET status = 'Revoked'
    WHERE id = p_code_id 
    AND (
        created_by = auth.uid()
        OR EXISTS (
            SELECT 1 FROM public.admissions a
            WHERE a.id = share_codes.admission_id
            AND (a.parent_id = auth.uid() OR a.parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid()))
        )
    );
END;
$$;

-- RPC: Admin/Parent Switch Student View
CREATE OR REPLACE FUNCTION public.parent_switch_student_view(p_new_admission_id UUID)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    -- This is largely a frontend state verification dummy in this simple schema.
    -- In a real app, you might log an audit event or verify access again.
    -- For now, we perform a read to ensure the parent actually has access.
    PERFORM 1 FROM public.admissions 
    WHERE admissions.id = p_new_admission_id; 
    -- If we used strict RLS, we'd add checks here.
END;
$$;


-- RPC: Get Student Dashboard Data
CREATE OR REPLACE FUNCTION public.get_student_dashboard_data(p_student_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_profile RECORD;
    v_admission RECORD;
    v_financials RECORD;
    v_attendance RECORD;
    v_timetable JSONB;
    v_assignments JSONB;
BEGIN
    -- 1. Fetch Basic Identity
    -- Try to find by Admission ID first (Applicant phase) or User ID (Enrolled phase)
    SELECT * INTO v_admission FROM public.admissions WHERE admissions.id = p_student_id OR student_user_id = p_student_id LIMIT 1;
    
    -- If no admission record, try looking up student profile directly
    IF v_admission IS NULL THEN
        SELECT * INTO v_admission FROM public.admissions WHERE student_user_id = p_student_id LIMIT 1;
    END IF;

    -- Fetch Profile data
    SELECT p.*, sp.grade, sp.roll_number, sp.enrollment_status 
    INTO v_profile 
    FROM public.profiles p
    LEFT JOIN public.student_profiles sp ON p.id = sp.user_id
    WHERE p.id = (v_admission.student_user_id) OR p.id = p_student_id;

    -- 2. Fetch Financials
    SELECT 
        COALESCE(SUM(amount) FILTER (WHERE status = 'Pending'), 0) as pending_dues,
        COALESCE(SUM(amount) FILTER (WHERE status = 'Paid'), 0) as paid_amount
    INTO v_financials
    FROM public.fee_invoices
    WHERE student_id = v_profile.id;

    -- 3. Fetch Attendance
    SELECT 
        COUNT(*) FILTER (WHERE status = 'Present') as present_days,
        COUNT(*) FILTER (WHERE status = 'Absent') as absent_days
    INTO v_attendance
    FROM public.attendance_records
    WHERE student_id = v_profile.id;

    -- 4. Construct Result
    RETURN jsonb_build_object(
        'profile', to_jsonb(v_profile),
        'admission', to_jsonb(v_admission),
        'financials', to_jsonb(v_financials),
        'attendance', to_jsonb(v_attendance),
        'needs_onboarding', (v_profile.profile_completed = false)
    );
END;
$$;


-- RPC: Get School Branches (For Admin Dashboard)
CREATE OR REPLACE FUNCTION public.get_school_branches()
RETURNS SETOF public.school_branches LANGUAGE sql SECURITY DEFINER AS $$
    SELECT * FROM public.school_branches ORDER BY is_main_branch DESC, name ASC;
$$;

-- RPC: Upsert Teacher Profile
CREATE OR REPLACE FUNCTION public.upsert_teacher_profile(
    p_user_id UUID,
    p_display_name TEXT,
    p_email TEXT,
    p_phone TEXT,
    p_department TEXT,
    p_designation TEXT,
    p_subject TEXT,
    p_qualification TEXT,
    p_experience INT,
    p_doj DATE
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    -- Update base profile
    UPDATE public.profiles 
    SET display_name = p_display_name, phone = p_phone, profile_completed = true 
    WHERE id = p_user_id;

    -- Upsert teacher details
    INSERT INTO public.teacher_profiles (user_id, subject_specialization, qualification, experience_years, bio, designation, department)
    VALUES (p_user_id, p_subject, p_qualification, p_experience, 'New Teacher', p_designation, p_department)
    ON CONFLICT (user_id) DO UPDATE SET
        subject_specialization = EXCLUDED.subject_specialization,
        qualification = EXCLUDED.qualification,
        experience_years = EXCLUDED.experience_years,
        designation = EXCLUDED.designation,
        department = EXCLUDED.department;
END;
$$;

-- RLS: Enhanced Parent Policies for Admissions
-- 1. SELECT: Parents view their own submissions
CREATE POLICY "Parents select own applications" ON public.admissions
    FOR SELECT USING (
        parent_id = auth.uid() 
        OR parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid())
    );

-- 2. INSERT: Parents can create new applications
CREATE POLICY "Parents insert own applications" ON public.admissions
    FOR INSERT WITH CHECK (
        parent_id = auth.uid()
        OR parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid())
    );

-- 3. UPDATE: Parents can update pending applications
CREATE POLICY "Parents update own applications" ON public.admissions
    FOR UPDATE USING (
        parent_id = auth.uid() 
        OR parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid())
    ) WITH CHECK (
        status IN ('Pending Review', 'Draft', 'ENQUIRY_ACTIVE') -- Only allow updates in early stages
    );

-- RLS: Document Vault Security
ALTER TABLE public.admission_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Parents manage own documents" ON public.admission_documents
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.admissions aa 
            WHERE aa.id = admission_documents.admission_id 
            AND (aa.parent_id = auth.uid() OR aa.parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid()))
        )
    );

-- RLS: Financial Transparency for Parents
CREATE POLICY "Parents view children invoices" ON public.fee_invoices
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.admissions aa 
            WHERE aa.student_user_id = fee_invoices.student_id 
            AND (aa.parent_id = auth.uid() OR aa.parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid()))
        )
    );

CREATE POLICY "Parents view children payments" ON public.fee_payments
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.admissions aa 
            WHERE aa.student_user_id = fee_payments.student_id 
            AND (aa.parent_id = auth.uid() OR aa.parent_email = (SELECT email FROM public.profiles WHERE profiles.id = auth.uid()))
        )
    );

-- RLS: Communication Inbox Access
ALTER TABLE public.communications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view relevant communications" ON public.communications
    FOR SELECT USING (
        sender_id = auth.uid()
        OR auth.uid()::text = ANY(recipients)
        -- OR check for role-based broadcast (simplified)
        OR (SELECT role FROM public.profiles WHERE profiles.id = auth.uid()) = ANY(recipients)
    );

-- RLS: Update Student Profile policies
CREATE POLICY "Parents can view their children's profiles" ON public.student_profiles
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.admissions aa 
            WHERE aa.student_user_id = student_profiles.user_id 
            AND (aa.parent_id = auth.uid() OR aa.parent_email = (SELECT email FROM public.profiles WHERE id = auth.uid()))
        )
    );

-- RPC: Switch Active Role (Critical for Role Selection & Identity Provisioning)
-- ===============================================================================================
CREATE OR REPLACE FUNCTION public.switch_active_role(p_target_role TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_profile_exists BOOLEAN := false;
    v_table_name TEXT;
    v_profile_completed BOOLEAN := false;
    v_onboarding_step TEXT := 'profile';
BEGIN
    -- 1. Identify target table based on role to check for existing context
    v_table_name := CASE p_target_role
        WHEN 'School Administration' THEN 'school_admin_profiles'
        WHEN 'Parent/Guardian' THEN 'parent_profiles'
        WHEN 'Student' THEN 'student_profiles'
        WHEN 'Teacher' THEN 'teacher_profiles'
        WHEN 'Accountant' THEN 'staff_profiles'
        WHEN 'HR Manager' THEN 'staff_profiles'
        WHEN 'Academic Coordinator' THEN 'staff_profiles'
        WHEN 'Principal' THEN 'staff_profiles'
        WHEN 'Transport Staff' THEN 'transport_profiles'
        WHEN 'Ecommerce Operator' THEN 'ecommerce_profiles'
        ELSE NULL
    END;

    -- 2. Performance-Aware Restoration Check
    IF v_table_name IS NOT NULL THEN
        EXECUTE format('SELECT EXISTS(SELECT 1 FROM public.%I WHERE user_id = $1)', v_table_name)
        INTO v_profile_exists
        USING auth.uid();

        -- Special handling for School Admin onboarding state
        IF p_target_role = 'School Administration' AND v_profile_exists THEN
            SELECT onboarding_step INTO v_onboarding_step 
            FROM public.school_admin_profiles 
            WHERE user_id = auth.uid();
            
            v_profile_completed := (v_onboarding_step = 'completed');
        ELSE
            v_profile_completed := v_profile_exists;
        END IF;
    END IF;

    -- 3. Atomic Identity Upgrade
    UPDATE public.profiles 
    SET role = p_target_role,
        profile_completed = v_profile_completed
    WHERE profiles.id = auth.uid();

    -- 4. Secure State Synchronization
    RETURN jsonb_build_object(
        'success', true,
        'profile_restored', v_profile_completed,
        'new_role', p_target_role,
        'onboarding_step', v_onboarding_step,
        'context_table', v_table_name
    );
END;
$$;

-- 15. STORAGE ACCESS CONTROL (BUCKET POLICIES)
-- ===============================================================================================
-- Note: These run on storage.objects

DROP POLICY IF EXISTS "Parents can upload documents" ON storage.objects;
DROP POLICY IF EXISTS "Parents can view their own documents" ON storage.objects;
DROP POLICY IF EXISTS "Public profile access" ON storage.objects;
DROP POLICY IF EXISTS "Users can upload own profile photos" ON storage.objects;
DROP POLICY IF EXISTS "Public avatar access" ON storage.objects;
DROP POLICY IF EXISTS "Users can upload own avatar" ON storage.objects;

CREATE POLICY "Parents can upload documents" ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'documents');

CREATE POLICY "Parents can view their own documents" ON storage.objects
    FOR SELECT TO authenticated
    USING (bucket_id = 'documents');

CREATE POLICY "Public profile access" ON storage.objects
    FOR SELECT TO public
    USING (bucket_id = 'profiles');

CREATE POLICY "Users can upload own profile photos" ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'profiles');

-- RPC: Get Admissions (Admin View)
DROP FUNCTION IF EXISTS public.get_admissions_v2(BIGINT) CASCADE;
CREATE OR REPLACE FUNCTION public.get_admissions_v2(p_branch_id BIGINT)
RETURNS TABLE (
    id UUID,
    applicant_name TEXT,
    grade TEXT,
    status TEXT,
    parent_name TEXT,
    parent_email TEXT,
    parent_phone TEXT,
    branch_id BIGINT,
    submitted_at TIMESTAMPTZ,
    profile_photo_url TEXT,
    date_of_birth DATE,
    gender TEXT,
    emergency_contact TEXT,
    medical_info TEXT
) LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY
    SELECT 
        aa.id,
        aa.applicant_name,
        aa.grade,
        aa.status,
        aa.parent_name,
        aa.parent_email,
        aa.parent_phone,
        aa.branch_id,
        aa.submitted_at,
        aa.profile_photo_url,
        aa.date_of_birth,
        aa.gender,
        aa.emergency_contact,
        aa.medical_info
    FROM public.admissions aa
    WHERE (p_branch_id IS NULL OR aa.branch_id = p_branch_id)
    ORDER BY aa.submitted_at DESC;
END;
$$;

-- Removed conflicting get_my_children_profiles overload

-- RPC: Request Documents
CREATE OR REPLACE FUNCTION public.admin_request_documents(
    p_admission_id UUID,
    p_documents TEXT[],
    p_message TEXT
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_doc TEXT;
BEGIN
    FOR v_doc IN SELECT unnest(p_documents) LOOP
        INSERT INTO public.document_requirements (admission_id, document_name, status)
        VALUES (p_admission_id, v_doc, 'Pending')
        ON CONFLICT DO NOTHING;
    END LOOP;

    -- Optional: Create a communication or notification for the parent
    -- INSERT INTO public.notifications (user_id, title, message, type) ...
END;
$$;

-- RPC: Finalize Enrollment (Core Logic)
DROP FUNCTION IF EXISTS public.admin_finalize_enrollment(UUID) CASCADE;
CREATE OR REPLACE FUNCTION public.admin_finalize_enrollment(p_admission_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_admission RECORD;
    v_student_id UUID;
    v_student_id_number TEXT;
BEGIN
    -- 1. Fetch Application context
    SELECT * INTO v_admission FROM public.admissions WHERE id = p_admission_id;
    IF v_admission IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Application node not found.');
    END IF;

    -- 2. Create Student Identity (Profiles table)
    -- If they don't have a user_id yet (external applicant), we might need to handle that, 
    -- but usually student_user_id is provisioned via Auth or a separate process.
    -- For now, if student_user_id is missing, we create a placeholder ID or return error.
    IF v_admission.student_user_id IS NULL THEN
        -- In a real system, we'd trigger a 'Create Student Account' flow here.
        -- For this simulation, we'll assume the student_user_id exists if they've registered.
        -- If not, we might need a workaround. Let's assume it exists for now.
        RETURN jsonb_build_object('success', false, 'message', 'Student User ID not provisioned. Account required.');
    END IF;

    v_student_id := v_admission.student_user_id;
    v_student_id_number := 'STU-' || v_admission.id::TEXT; -- Simplified

    -- 3. Update Base Profile
    UPDATE public.profiles 
    SET role = 'Student', profile_photo_url = v_admission.profile_photo_url 
    WHERE id = v_student_id;

    -- 4. Create specialized Student Profile
    INSERT INTO public.student_profiles (
        user_id, grade, date_of_birth, gender, branch_id, 
        enrollment_status, student_id_number, emergency_contact, medical_info
    ) VALUES (
        v_student_id, v_admission.grade, v_admission.date_of_birth, v_admission.gender, v_admission.branch_id,
        'Enrolled', v_student_id_number, v_admission.emergency_contact, v_admission.medical_info
    ) ON CONFLICT (user_id) DO UPDATE SET
        enrollment_status = 'Enrolled',
        student_id_number = EXCLUDED.student_id_number;

    -- 5. Finalize Application status
    UPDATE public.admissions SET status = 'Approved' WHERE id = p_admission_id;

    RETURN jsonb_build_object(
        'success', true, 
        'student_id', v_student_id, 
        'student_id_number', v_student_id_number
    );
END;
$$;

-- ===============================================================================================
-- INSTITUTIONAL SETUP & BRANCH HYPER-PROTOCOL
-- ===============================================================================================

-- RPC: Initialize School Admin
CREATE OR REPLACE FUNCTION public.initialize_school_admin()
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    -- Identity provisioning for the global node
    UPDATE public.profiles 
    SET role = 'School Administration', profile_completed = false
    WHERE id = auth.uid();

    -- Context metadata initialization
    INSERT INTO public.school_admin_profiles (user_id, onboarding_step)
    VALUES (auth.uid(), 'profile')
    ON CONFLICT (user_id) DO NOTHING;
END;
$$;

-- RPC: Create School Branch
CREATE OR REPLACE FUNCTION public.create_school_branch(
    p_name TEXT,
    p_address TEXT,
    p_city TEXT,
    p_state TEXT,
    p_country TEXT,
    p_contact_number TEXT,
    p_is_main BOOLEAN,
    p_email TEXT,
    p_admin_name TEXT,
    p_admin_phone TEXT,
    p_admin_email TEXT
) RETURNS SETOF public.school_branches LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_branch_id BIGINT;
BEGIN
    -- Global Singleton Check for Main Branch
    IF p_is_main THEN
        UPDATE public.school_branches SET is_main_branch = false WHERE id IN (SELECT id FROM public.school_branches WHERE is_main_branch = true);
    END IF;

    INSERT INTO public.school_branches (
        name, address, city, state, country, is_main_branch, admin_email, access_key, school_id, status
    ) VALUES (
        p_name, p_address, p_city, p_state, p_country, p_is_main, p_admin_email, 
        upper(substr(md5(random()::text), 1, 8)), auth.uid(), 'Pending'
    ) RETURNING id INTO v_branch_id;

    RETURN QUERY SELECT * FROM public.school_branches WHERE id = v_branch_id;
END;
$$;


-- RPC: Get School Branches
CREATE OR REPLACE FUNCTION public.get_school_branches()
RETURNS SETOF public.school_branches LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY SELECT * FROM public.school_branches 
    WHERE school_id = auth.uid()
    ORDER BY is_main_branch DESC, created_at ASC;
END;
$$;

-- RPC: Update School Branch
CREATE OR REPLACE FUNCTION public.update_school_branch(
    p_branch_id BIGINT,
    p_name TEXT,
    p_address TEXT,
    p_city TEXT,
    p_state TEXT,
    p_country TEXT,
    p_contact_number TEXT,
    p_is_main BOOLEAN,
    p_email TEXT,
    p_admin_name TEXT,
    p_admin_phone TEXT,
    p_admin_email TEXT
) RETURNS SETOF public.school_branches LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    -- Synchronization protocol for singleton main branch
    IF p_is_main THEN
        UPDATE public.school_branches SET is_main_branch = false WHERE id <> p_branch_id;
    END IF;

    UPDATE public.school_branches SET
        name = p_name,
        address = p_address,
        city = p_city,
        state = p_state,
        country = p_country,
        is_main_branch = p_is_main,
        admin_email = p_admin_email,
        updated_at = NOW()
    WHERE id = p_branch_id;


    RETURN QUERY SELECT * FROM public.school_branches WHERE id = p_branch_id;
END;
$$;

-- RPC: Delete School Branch
CREATE OR REPLACE FUNCTION public.delete_school_branch(p_branch_id BIGINT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    DELETE FROM public.school_branches WHERE id = p_branch_id;
END;
$$;

-- RPC: Complete Branch Onboarding Step
CREATE OR REPLACE FUNCTION public.complete_branch_step()
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    -- Finalize institutional identity
    UPDATE public.school_admin_profiles 
    SET onboarding_step = 'completed'
    WHERE user_id = auth.uid();
    
    UPDATE public.profiles
    SET profile_completed = true
    WHERE id = auth.uid();
END;
$$;

-- RPC: Update School Plan & Progress Onboarding
CREATE OR REPLACE FUNCTION public.update_school_plan(p_plan_id TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    UPDATE public.school_admin_profiles SET
        base_plan_id = p_plan_id,
        onboarding_step = 'branches'
    WHERE user_id = auth.uid();
END;
$$;

-- RPC: Verify and Link Branch Admin
CREATE OR REPLACE FUNCTION public.verify_and_link_branch_admin(p_invitation_code TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_branch_id BIGINT;
BEGIN
    SELECT id INTO v_branch_id 
    FROM public.school_branches 
    WHERE access_key = p_invitation_code 
      AND (status = 'Active' OR status = 'Pending');

    IF v_branch_id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'The Access Key provided is invalid, expired, or not authorized for this identity.');
    END IF;

    -- Update branch status to Active (Linked)
    UPDATE public.school_branches SET status = 'Active' WHERE id = v_branch_id;

    UPDATE public.profiles SET
        branch_id = v_branch_id,
        role = 'School Administration',
        profile_completed = true
    WHERE id = auth.uid();

    -- Ensure specialized profile exists
    INSERT INTO public.school_admin_profiles (user_id, onboarding_step)
    VALUES (auth.uid(), 'completed')
    ON CONFLICT (user_id) DO UPDATE SET onboarding_step = 'completed';

    RETURN jsonb_build_object('success', true, 'branch_id', v_branch_id);
END;
$$;

-- Parent Portal RPCs
CREATE OR REPLACE FUNCTION public.get_parent_dashboard_stats()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_total INT;
    v_pending INT;
    v_approved INT;
BEGIN
    SELECT count(*) INTO v_total FROM public.admissions WHERE parent_id = auth.uid();
    SELECT count(*) INTO v_pending FROM public.admissions WHERE parent_id = auth.uid() AND status NOT IN ('Approved', 'Verified', 'Enrolled');
    SELECT count(*) INTO v_approved FROM public.admissions WHERE parent_id = auth.uid() AND status IN ('Approved', 'Verified', 'Enrolled');
    
    RETURN jsonb_build_object(
        'total_applications', v_total,
        'pending_applications', v_pending,
        'approved_applications', v_approved
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_my_messages()
RETURNS SETOF public.communications LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY 
    SELECT * FROM public.communications 
    WHERE recipient_role = 'Parent/Guardian'
    OR recipient_id = auth.uid()
    ORDER BY sent_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_my_enquiries()
RETURNS SETOF public.admissions LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN QUERY
    SELECT * FROM public.admissions
    WHERE parent_id = auth.uid()
    OR (parent_email IS NOT NULL AND parent_email = (SELECT email FROM public.profiles WHERE id = auth.uid()))
    ORDER BY updated_at DESC;
END;
$$;

