-- =====================================================================================================
-- FINANCE ENTERPRISE MODULES V1
-- Description: Adds tables and functions for Refunds, Waivers, Period Locks, and Late Fees
-- Author: Antigravity Agent
-- Date: 2026-02-19
-- =====================================================================================================

-- 1. REFUND MANAGEMENT
-- -----------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance_refund_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES school_branches(id),
    student_id UUID REFERENCES student_profiles(user_id),
    invoice_id BIGINT, -- Optional reference to original invoice
    amount DECIMAL(15,2) NOT NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'INITIATED' CHECK (status IN ('INITIATED', 'PENDING_APPROVAL', 'APPROVED', 'PROCESSED', 'REJECTED')),
    requested_by UUID REFERENCES auth.users(id),
    approved_by UUID REFERENCES auth.users(id),
    processed_at TIMESTAMPTZ,
    refund_method TEXT CHECK (refund_method IN ('BANK_TRANSFER', 'CHEQUE', 'CREDIT_NOTE')),
    reference_number TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster lookup
CREATE INDEX IF NOT EXISTS idx_refunds_branch ON finance_refund_requests(branch_id);
CREATE INDEX IF NOT EXISTS idx_refunds_student ON finance_refund_requests(student_id);
CREATE INDEX IF NOT EXISTS idx_refunds_status ON finance_refund_requests(status);

-- 2. WAIVER MANAGEMENT
-- -----------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance_waiver_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES school_branches(id),
    student_id UUID REFERENCES student_profiles(user_id),
    fee_structure_id BIGINT REFERENCES finance_fee_structures(id),
    waiver_type TEXT NOT NULL CHECK (waiver_type IN ('PERCENTAGE', 'FLAT', 'FULL')),
    waiver_value DECIMAL(15,2) NOT NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')),
    applied_by UUID REFERENCES auth.users(id),
    approved_by UUID REFERENCES auth.users(id),
    valid_from DATE,
    valid_to DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_waivers_branch ON finance_waiver_applications(branch_id);
CREATE INDEX IF NOT EXISTS idx_waivers_student ON finance_waiver_applications(student_id);

-- 3. FINANCIAL PERIOD LOCKS
-- -----------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance_financial_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES school_branches(id),
    name TEXT NOT NULL, -- e.g., "April 2026", "Q1 2026"
    period_type TEXT NOT NULL CHECK (period_type IN ('MONTHLY', 'QUARTERLY', 'ANNUAL')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'LOCKED', 'CLOSED')),
    locked_by UUID REFERENCES auth.users(id),
    locked_at TIMESTAMPTZ,
    notes TEXT,
    total_revenue_snapshot DECIMAL(20,2), -- Snapshot at closing
    total_expense_snapshot DECIMAL(20,2)  -- Snapshot at closing
);

CREATE INDEX IF NOT EXISTS idx_periods_branch ON finance_financial_periods(branch_id);

-- 4. LATE FEE CONFIGURATION
-- -----------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS finance_late_fee_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES school_branches(id),
    name TEXT NOT NULL,
    fee_structure_id BIGINT REFERENCES finance_fee_structures(id), -- Specific rule for specific structure, or null for global
    grace_period_days INT NOT NULL DEFAULT 0,
    fee_type TEXT NOT NULL CHECK (fee_type IN ('PERCENTAGE', 'FLAT')),
    fee_value DECIMAL(10,2) NOT NULL,
    max_cap DECIMAL(10,2), -- Maximum late fee amount
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. AUDIT LOGGING TRIGGERS (Generic function to log to finance_audit_logs)
-- -----------------------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_log_finance_audit()
RETURNS TRIGGER AS $$
DECLARE
    v_user_id UUID;
    v_user_name TEXT;
    v_branch_id BIGINT;
    v_action TEXT;
    v_desc TEXT;
BEGIN
    -- Attempt to get current user
    BEGIN
        v_user_id := auth.uid();
    EXCEPTION WHEN OTHERS THEN
        v_user_id := NULL;
    END;

    -- If no user, default to system
    IF v_user_id IS NULL THEN
        v_user_name := 'SYSTEM_AUTOMATION';
    ELSE
        -- Try to fetch name from profiles (adjust table name if needed)
        SELECT display_name INTO v_user_name FROM profiles WHERE id = v_user_id;
        IF v_user_name IS NULL THEN v_user_name := 'UNKNOWN_USER'; END IF;
    END IF;

    IF TG_OP = 'INSERT' THEN
        v_branch_id := NEW.branch_id;
        v_action := 'CREATE';
        v_desc := 'Created new record in ' || TG_TABLE_NAME;
    ELSIF TG_OP = 'UPDATE' THEN
        v_branch_id := NEW.branch_id;
        v_action := 'UPDATE';
        v_desc := 'Updated record in ' || TG_TABLE_NAME;
    ELSIF TG_OP = 'DELETE' THEN
        v_branch_id := OLD.branch_id;
        v_action := 'DELETE';
        v_desc := 'Deleted record from ' || TG_TABLE_NAME;
    END IF;

    INSERT INTO finance_audit_logs (
        branch_id,
        module,
        action,
        description,
        entity_type,
        entity_id,
        old_value,
        new_value,
        performed_by,
        performed_by_name,
        severity
    ) VALUES (
        v_branch_id,
        'ENTERPRISE_FINANCE',
        v_action || '_' || TG_TABLE_NAME,
        v_desc,
        TG_TABLE_NAME,
        COALESCE(NEW.id, OLD.id)::TEXT,
        CASE WHEN TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN row_to_json(OLD) ELSE NULL END,
        CASE WHEN TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN row_to_json(NEW) ELSE NULL END,
        v_user_id,
        v_user_name,
        'MEDIUM'
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Apply triggers
DROP TRIGGER IF EXISTS trg_audit_refunds ON finance_refund_requests;
CREATE TRIGGER trg_audit_refunds
AFTER INSERT OR UPDATE OR DELETE ON finance_refund_requests
FOR EACH ROW EXECUTE FUNCTION fn_log_finance_audit();

DROP TRIGGER IF EXISTS trg_audit_waivers ON finance_waiver_applications;
CREATE TRIGGER trg_audit_waivers
AFTER INSERT OR UPDATE OR DELETE ON finance_waiver_applications
FOR EACH ROW EXECUTE FUNCTION fn_log_finance_audit();

DROP TRIGGER IF EXISTS trg_audit_periods ON finance_financial_periods;
CREATE TRIGGER trg_audit_periods
AFTER INSERT OR UPDATE OR DELETE ON finance_financial_periods
FOR EACH ROW EXECUTE FUNCTION fn_log_finance_audit();

-- 6. RPCs for Frontend Access
-- -----------------------------------------------------------------------------------------------------

-- Get Refunds
CREATE OR REPLACE FUNCTION get_refund_requests(p_branch_id BIGINT)
RETURNS SETOF finance_refund_requests AS $$
BEGIN
    RETURN QUERY SELECT * FROM finance_refund_requests
    WHERE (p_branch_id IS NULL OR branch_id = p_branch_id)
    ORDER BY created_at DESC;
END;
$$ LANGUAGE plpgsql;

-- Get Waivers
CREATE OR REPLACE FUNCTION get_waiver_applications(p_branch_id BIGINT)
RETURNS SETOF finance_waiver_applications AS $$
BEGIN
    RETURN QUERY SELECT * FROM finance_waiver_applications
    WHERE (p_branch_id IS NULL OR branch_id = p_branch_id)
    ORDER BY created_at DESC;
END;
$$ LANGUAGE plpgsql;

-- Get Periods
CREATE OR REPLACE FUNCTION get_financial_periods(p_branch_id BIGINT)
RETURNS SETOF finance_financial_periods AS $$
BEGIN
    RETURN QUERY SELECT * FROM finance_financial_periods
    WHERE (p_branch_id IS NULL OR branch_id = p_branch_id)
    ORDER BY start_date DESC;
END;
$$ LANGUAGE plpgsql;
