-- =============================================================================
-- 🛠️ FINANCE V47: AUDIT LOG SCHEMA SYNCHRONIZATION 🛠️
-- =============================================================================
-- Date: 2026-02-20
-- Objective: Fix "Attribute Desync: column branch_id does not exist" in finance_audit_logs.
-- Strategy: Unify conflicting audit log definitions from multiple legacy scripts.
-- =============================================================================

BEGIN;

DO $$
BEGIN
    -- 1. Ensure finance_audit_logs exists (Fallback)
    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'finance_audit_logs') THEN
        CREATE TABLE public.finance_audit_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
        RAISE NOTICE 'Created base finance_audit_logs table.';
    END IF;

    -- 2. Add branch_id (The critical missing column)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'finance_audit_logs' AND column_name = 'branch_id') THEN
        ALTER TABLE public.finance_audit_logs ADD COLUMN branch_id BIGINT;
        RAISE NOTICE 'Added branch_id to finance_audit_logs.';
    END IF;

    -- 3. Add other missing columns used by fn_activate_finance_structure
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'finance_audit_logs' AND column_name = 'module') THEN
        ALTER TABLE public.finance_audit_logs ADD COLUMN module TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'finance_audit_logs' AND column_name = 'action') THEN
        ALTER TABLE public.finance_audit_logs ADD COLUMN action TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'finance_audit_logs' AND column_name = 'entity_type') THEN
        ALTER TABLE public.finance_audit_logs ADD COLUMN entity_type TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'finance_audit_logs' AND column_name = 'entity_id') THEN
        ALTER TABLE public.finance_audit_logs ADD COLUMN entity_id TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'finance_audit_logs' AND column_name = 'performed_by') THEN
        ALTER TABLE public.finance_audit_logs ADD COLUMN performed_by UUID;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'finance_audit_logs' AND column_name = 'severity') THEN
        ALTER TABLE public.finance_audit_logs ADD COLUMN severity TEXT DEFAULT 'INFO';
    END IF;

    -- 4. Re-grant permissions
    GRANT ALL ON public.finance_audit_logs TO authenticated;
    
END $$;

COMMIT;

SELECT 'SUCCESS: Finance V47 Audit Log Sync deployed. branch_id error resolved.' AS status;
