-- =============================================================================
-- 🛠️ FINANCE V45: IDENTITY OVERRIDE (RESILIENT VERSION) 🛠️
-- =============================================================================
-- Date: 2026-02-20
-- Objective: Safely convert identity columns to 'BY DEFAULT' while ignoring 
--            errors for tables that already use SERIAL or plain columns.
-- =============================================================================

BEGIN;

-- 1. Fix finance_fee_structures
DO $$
BEGIN
    BEGIN
        -- Attempt to change to BY DEFAULT only if it's an identity column
        IF EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_schema = 'public' 
              AND table_name = 'finance_fee_structures' 
              AND column_name = 'id' 
              AND is_identity = 'YES'
        ) THEN
            ALTER TABLE public.finance_fee_structures ALTER COLUMN id SET GENERATED BY DEFAULT;
            RAISE NOTICE 'Converted finance_fee_structures.id to BY DEFAULT';
        ELSE
            RAISE NOTICE 'finance_fee_structures.id is not an identity column, skipping conversion.';
        END IF;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Error during structures fix: %', SQLERRM;
    END;
END $$;

-- 2. Fix finance_fee_components
DO $$
BEGIN
    BEGIN
        -- Attempt to change to BY DEFAULT only if it's an identity column
        IF EXISTS (
            SELECT 1 FROM information_schema.columns 
            WHERE table_schema = 'public' 
              AND table_name = 'finance_fee_components' 
              AND column_name = 'id' 
              AND is_identity = 'YES'
        ) THEN
            ALTER TABLE public.finance_fee_components ALTER COLUMN id SET GENERATED BY DEFAULT;
            RAISE NOTICE 'Converted finance_fee_components.id to BY DEFAULT';
        ELSE
            RAISE NOTICE 'finance_fee_components.id is not an identity column, skipping conversion.';
        END IF;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Error during components fix: %', SQLERRM;
    END;
END $$;

COMMIT;

SELECT 'SUCCESS: Identity check complete. Any "ALWAYS" identity columns have been converted to "BY DEFAULT". Tables using SERIAL or manual IDs were skipped safely.' AS status;
