-- ==============================================================================
-- FINANCE PHASE 1: MASTER PROTOCOL INITIALIZATION
-- ==============================================================================
-- Description: Standardizes schema, adds audit/validation logic.
-- ==============================================================================

BEGIN;

-- 1. SCHEMA STANDARDIZATION (Migration)
-- ------------------------------------------------------------------------------

-- Rename fee_structures -> finance_fee_structures if exists
DO $$
BEGIN
    -- Handle fee_structures rename safely
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'fee_structures') THEN
        IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'finance_fee_structures') THEN
            ALTER TABLE public.fee_structures RENAME TO finance_fee_structures;
        ELSE
            RAISE NOTICE 'Target table finance_fee_structures already exists. Skipping rename of fee_structures.';
        END IF;
    END IF;

    -- Handle fee_components rename safely
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'fee_components') THEN
        IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'finance_fee_components') THEN
            ALTER TABLE public.fee_components RENAME TO finance_fee_components;
        ELSE
            RAISE NOTICE 'Target table finance_fee_components already exists. Skipping rename of fee_components.';
        END IF;
    END IF;
END $$;

-- Ensure finance_fee_structures exists with V2 columns
CREATE TABLE IF NOT EXISTS public.finance_fee_structures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.school_branches(id),
    name TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    target_grade TEXT NOT NULL,
    description TEXT,
    currency TEXT DEFAULT 'INR',
    is_default BOOLEAN DEFAULT FALSE,
    type TEXT DEFAULT 'Standard',
    status TEXT DEFAULT 'Draft', -- Draft, Active, Archived
    version INTEGER DEFAULT 1,
    is_locked BOOLEAN DEFAULT FALSE,
    locked_at TIMESTAMPTZ,
    locked_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure finance_fee_components exists
CREATE TABLE IF NOT EXISTS public.finance_fee_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id BIGINT REFERENCES public.finance_fee_structures(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    amount DECIMAL(15,2) DEFAULT 0,
    frequency TEXT DEFAULT 'Monthly', -- One-time, Monthly, Quarterly, Annually
    is_mandatory BOOLEAN DEFAULT TRUE,
    category TEXT DEFAULT 'Tuition',
    gl_code TEXT,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    is_refundable BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Backfill missing columns if table existed but was old
DO $$
BEGIN
    -- finance_fee_structures
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='finance_fee_structures' AND column_name='is_locked') THEN
        ALTER TABLE public.finance_fee_structures ADD COLUMN is_locked BOOLEAN DEFAULT FALSE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='finance_fee_structures' AND column_name='version') THEN
        ALTER TABLE public.finance_fee_structures ADD COLUMN version INTEGER DEFAULT 1;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='finance_fee_structures' AND column_name='locked_at') THEN
        ALTER TABLE public.finance_fee_structures ADD COLUMN locked_at TIMESTAMPTZ;
    END IF;
     IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='finance_fee_structures' AND column_name='locked_by') THEN
        ALTER TABLE public.finance_fee_structures ADD COLUMN locked_by UUID REFERENCES auth.users(id);
    END IF;
END $$;


-- 2. FINANCIAL PERIODS & AUDIT LOGS
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.finance_financial_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.school_branches(id),
    name TEXT NOT NULL,
    period_type TEXT NOT NULL CHECK (period_type IN ('MONTHLY', 'QUARTERLY', 'ANNUAL')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'LOCKED', 'CLOSED')),
    locked_by UUID REFERENCES auth.users(id),
    locked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.finance_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.school_branches(id),
    module TEXT NOT NULL,
    action TEXT NOT NULL,
    description TEXT,
    entity_type TEXT,
    entity_id TEXT,
    old_value JSONB,
    new_value JSONB,
    performed_by UUID REFERENCES auth.users(id),
    performed_by_name TEXT,
    severity TEXT DEFAULT 'INFO',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. VALIDATION ENGINE RPC
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_validate_finance_master_activation(p_structure_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_structure RECORD;
    v_component_count INTEGER;
    v_components_without_gl INTEGER;
    v_result JSONB;
    v_errors TEXT[] := ARRAY[]::TEXT[];
    v_warnings TEXT[] := ARRAY[]::TEXT[];
BEGIN
    -- Fetch Structure
    SELECT * INTO v_structure FROM public.finance_fee_structures WHERE id = p_structure_id;
    
    IF v_structure IS NULL THEN
        RETURN jsonb_build_object('ready', false, 'errors', ARRAY['Structure not found']);
    END IF;

    -- Rule 1: Must have components
    SELECT COUNT(*) INTO v_component_count FROM public.finance_fee_components WHERE structure_id = p_structure_id;
    IF v_component_count = 0 THEN
        v_errors := array_append(v_errors, 'Structure has no fee components linked.');
    END IF;

    -- Rule 2: All components must have GL Code (Revenue Account)
    SELECT COUNT(*) INTO v_components_without_gl 
    FROM public.finance_fee_components 
    WHERE structure_id = p_structure_id AND (gl_code IS NULL OR gl_code = '');
    
    IF v_components_without_gl > 0 THEN
        v_errors := array_append(v_errors, v_components_without_gl || ' components are missing Revenue Account (GL Code) mapping.');
    END IF;

    -- Rule 3: Check Duplicate Active Structure (Same Grade & Year)
    IF EXISTS (
        SELECT 1 FROM public.finance_fee_structures 
        WHERE branch_id = v_structure.branch_id 
          AND target_grade = v_structure.target_grade 
          AND academic_year = v_structure.academic_year
          AND status = 'Active'
          AND id != p_structure_id
    ) THEN
        v_errors := array_append(v_errors, 'Another Active structure already exists for ' || v_structure.target_grade || ' in ' || v_structure.academic_year);
    END IF;

    -- Build Result
    v_result := jsonb_build_object(
        'ready', (array_length(v_errors, 1) IS NULL),
        'errors', COALESCE(v_errors, ARRAY[]::TEXT[]),
        'warnings', COALESCE(v_warnings, ARRAY[]::TEXT[])
    );

    RETURN v_result;
END;
$$;


-- 4. ACTIVATION RPC
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_activate_finance_structure(
    p_structure_id BIGINT,
    p_user_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_validation JSONB;
    v_structure RECORD;
BEGIN
    -- 1. Run Validation
    v_validation := public.fn_validate_finance_master_activation(p_structure_id);
    
    IF (v_validation->>'ready')::BOOLEAN = FALSE THEN
        RETURN jsonb_build_object('success', false, 'validation', v_validation);
    END IF;

    -- 2. Lock & Activate
    UPDATE public.finance_fee_structures
    SET status = 'Active',
        is_locked = TRUE,
        locked_at = NOW(),
        locked_by = p_user_id,
        updated_at = NOW()
    WHERE id = p_structure_id
    RETURNING * INTO v_structure;

    -- 3. Log Audit
    INSERT INTO public.finance_audit_logs (
        branch_id, module, action, description, entity_type, entity_id, performed_by, severity
    ) VALUES (
        v_structure.branch_id,
        'FINANCE_MASTER',
        'ACTIVATE_STRUCTURE',
        'Activated Fee Structure: ' || v_structure.name || ' (' || v_structure.target_grade || ')',
        'finance_fee_structures',
        v_structure.id::TEXT,
        p_user_id,
        'CRITICAL'
    );

    RETURN jsonb_build_object('success', true, 'structure', row_to_json(v_structure));
END;
$$;

COMMIT;
