-- ==============================================================================
-- FIX: Course Creation Master Fix V2
-- Description: Consolidates all fixes for course creation (single & bulk).
--              Ensures branch_id presence, tables exist, RLS policies, and robust RPCs.
-- ==============================================================================

-- 1. UTILITY: Ensure get_my_branch_ids exists and is correct
CREATE OR REPLACE FUNCTION public.get_my_branch_ids()
RETURNS SETOF bigint
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    -- 1. Direct Branch Admin / School Admin ownership
    -- (We check checks for columns existence dynamically would be complex in SQL function, 
    -- so we assume schema is standard. If errors occur, columns might be missing)
    SELECT id FROM public.school_branches 
    WHERE school_user_id = auth.uid() OR branch_admin_id = auth.uid()
    
    UNION
    
    -- 2. Role Assignments
    SELECT branch_id FROM public.user_role_assignments
    WHERE user_id = auth.uid()
    
    UNION
    
    -- 3. Profile Link (for Teachers/Students/Parents)
    SELECT branch_id FROM public.profiles 
    WHERE id = auth.uid() AND branch_id IS NOT NULL;
$$;

-- 2. TABLE: Ensure courses table has branch_id
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'courses' AND column_name = 'branch_id') THEN
        ALTER TABLE public.courses ADD COLUMN branch_id bigint REFERENCES public.school_branches(id);
    END IF;
END $$;

-- 3. TABLE: Ensure course_modules exists
CREATE TABLE IF NOT EXISTS public.course_modules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
    title text NOT NULL,
    duration_hours numeric DEFAULT 0,
    order_index integer DEFAULT 0,
    status text DEFAULT 'Active',
    created_at timestamptz DEFAULT now()
);

-- 4. TABLE: Ensure course_logs exists
CREATE TABLE IF NOT EXISTS public.course_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.profiles(id),
    action text NOT NULL,
    details jsonb,
    created_at timestamptz DEFAULT now()
);

-- 5. RLS: Enable and Configure
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_modules ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Admins can manage courses in their branch" ON public.courses;
DROP POLICY IF EXISTS "Users can view courses in their branch" ON public.courses;
DROP POLICY IF EXISTS "Authenticated users can view courses" ON public.courses;
DROP POLICY IF EXISTS "Create courses" ON public.courses;

-- Policy: View (All authenticated users in the branch)
CREATE POLICY "Users can view courses in their branch" ON public.courses
FOR SELECT
USING (
    branch_id IN (SELECT public.get_my_branch_ids())
);

-- Policy: Manage (Admins/Principals/Coordinators)
CREATE POLICY "Admins can manage courses in their branch" ON public.courses
FOR ALL
USING (
    branch_id IN (SELECT public.get_my_branch_ids())
    AND (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() 
            AND role IN ('School Administration', 'Branch Admin', 'Super Admin', 'Academic Coordinator', 'Principal')
        )
        OR
        EXISTS (
            SELECT 1 FROM public.user_role_assignments
            WHERE user_id = auth.uid() AND branch_id = courses.branch_id
            AND role_name IN ('School Administration', 'Branch Admin', 'Academic Coordinator', 'Principal')
        )
    )
);

-- RLS for Modules (Inherit from Course)
CREATE POLICY "Inherit course visibility" ON public.course_modules
FOR ALL
USING (
    EXISTS (
        SELECT 1 FROM public.courses c
        WHERE c.id = course_modules.course_id
        AND c.branch_id IN (SELECT public.get_my_branch_ids())
    )
);

-- 6. RPC: create_course_with_modules (SINGLE CREATION)
CREATE OR REPLACE FUNCTION public.create_course_with_modules(
    p_course_data jsonb,
    p_modules_data jsonb,
    p_branch_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_course_id bigint;
    v_module jsonb;
    v_order int := 1;
    v_teacher_id uuid;
    v_credits numeric;
BEGIN
    -- 1. Validate Branch Access
    IF NOT EXISTS (
        SELECT 1 FROM public.school_branches 
        WHERE id = p_branch_id 
        AND id IN (SELECT public.get_my_branch_ids())
    ) THEN
        RAISE EXCEPTION 'Unauthorized: You do not have permission to create courses in this branch.';
    END IF;

    -- 2. Prepare Data
    -- Handle teacher_id being empty string or null
    IF (p_course_data->>'teacher_id') IS NULL OR (p_course_data->>'teacher_id') = '' THEN
        v_teacher_id := NULL;
    ELSE
        v_teacher_id := (p_course_data->>'teacher_id')::uuid;
    END IF;
    
    -- Handle credits default
    v_credits := COALESCE((p_course_data->>'credits')::numeric, 3);

    -- 3. Insert Course
    INSERT INTO public.courses (
        title,
        code,
        description,
        credits,
        category,
        grade_level,
        status,
        teacher_id,
        department,
        subject_type,
        branch_id,
        created_at
    ) VALUES (
        p_course_data->>'title',
        p_course_data->>'code',
        p_course_data->>'description',
        v_credits,
        p_course_data->>'category',
        p_course_data->>'grade_level',
        p_course_data->>'status',
        v_teacher_id,
        p_course_data->>'department',
        p_course_data->>'subject_type',
        p_branch_id,
        now()
    )
    RETURNING id INTO v_course_id;

    -- 4. Insert Modules (if any)
    IF p_modules_data IS NOT NULL AND jsonb_array_length(p_modules_data) > 0 THEN
        FOR v_module IN SELECT * FROM jsonb_array_elements(p_modules_data)
        LOOP
            INSERT INTO public.course_modules (
                course_id,
                title,
                duration_hours,
                order_index,
                status
            ) VALUES (
                v_course_id,
                v_module->>'title',
                COALESCE((v_module->>'hours')::numeric, 0),
                v_order,
                'Active'
            );
            v_order := v_order + 1;
        END LOOP;
    END IF;

    -- 5. Log Action (if table exists)
    BEGIN
        INSERT INTO public.course_logs (course_id, user_id, action, details)
        VALUES (
            v_course_id,
            auth.uid(),
            'CREATED',
            jsonb_build_object('title', p_course_data->>'title', 'modules_count', v_order - 1)
        );
    EXCEPTION WHEN undefined_table THEN
        -- Ignore if log table doesn't exist
        NULL;
    END;

    RETURN jsonb_build_object('id', v_course_id, 'success', true);
END;
$$;

-- 7. RPC: bulk_import_courses (BULK CREATION)
CREATE OR REPLACE FUNCTION public.bulk_import_courses(p_courses jsonb, p_branch_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    course_data jsonb;
    success_count int := 0;
    failure_count int := 0;
    errors jsonb[] := ARRAY[]::jsonb[];
    v_credits numeric;
BEGIN
    -- Validate branch_id
    IF p_branch_id IS NULL THEN
        RAISE EXCEPTION 'Branch ID is required for course import';
    END IF;

    -- Verify user has access to this branch
    IF NOT EXISTS (
        SELECT 1 FROM public.school_branches 
        WHERE id = p_branch_id 
        AND id IN (SELECT public.get_my_branch_ids())
    ) THEN
        RAISE EXCEPTION 'Unauthorized: You do not have access to this branch. Please verify your branch assignment.';
    END IF;

    FOR course_data IN SELECT * FROM jsonb_array_elements(p_courses)
    LOOP
        BEGIN
            v_credits := COALESCE((course_data->>'credits')::numeric, 3);
            
            INSERT INTO public.courses (
                title, 
                code, 
                grade_level, 
                description, 
                category, 
                credits, 
                status, 
                department,
                branch_id,
                created_at
            ) VALUES (
                course_data->>'title',
                course_data->>'code',
                course_data->>'grade_level',
                course_data->>'description',
                COALESCE(course_data->>'category', 'Core'),
                v_credits,
                'Active',
                course_data->>'department',
                p_branch_id,
                now()
            );
            success_count := success_count + 1;
        EXCEPTION WHEN OTHERS THEN
            failure_count := failure_count + 1;
            errors := array_append(errors, jsonb_build_object(
                'row_index', (course_data->>'row_index')::int,
                'title', course_data->>'title',
                'error', SQLERRM
            ));
        END;
    END LOOP;

    RETURN jsonb_build_object(
        'success_count', success_count,
        'failure_count', failure_count,
        'errors', to_jsonb(errors)
    );
END;
$$;

-- 8. Permissions
GRANT ALL ON public.courses TO authenticated;
GRANT ALL ON public.course_modules TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_branch_ids TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_course_with_modules TO authenticated;
GRANT EXECUTE ON FUNCTION public.bulk_import_courses TO authenticated;
