-- ==============================================================================
-- FIX: Course Schema, RLS, & Data Persistence (FULL SYNC)
-- Description: 
-- 1. Adds missing columns for detailed course data.
-- 2. Updates `create_course_with_modules` to persist all form fields.
-- 3. Updates `bulk_import_courses` to handle new fields and arrays.
-- 4. Fixes RLS policies to ensure courses are visible to branch users.
-- ==============================================================================

-- 1. UTILITY: Robust Branch Access (Fix for Super Admins and Staff)
CREATE OR REPLACE FUNCTION public.get_my_branch_ids()
RETURNS SETOF bigint
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    -- 1. Super Admin AND School Admin sees ALL branches (Broad fix for admin visibility)
    SELECT id FROM public.school_branches 
    WHERE EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND (role = 'Super Admin' OR role = 'School Administration'))
    
    UNION
    
    -- 2. Direct Branch Admin / School Admin ownership
    SELECT id FROM public.school_branches 
    WHERE school_user_id = auth.uid() OR branch_admin_id = auth.uid()
    
    UNION
    
    -- 3. Role Assignments (Staff/Admins)
    SELECT branch_id FROM public.user_role_assignments
    WHERE user_id = auth.uid()
    
    UNION
    
    -- 4. Profile Link (Teachers/Students/Parents)
    SELECT branch_id FROM public.profiles 
    WHERE id = auth.uid() AND branch_id IS NOT NULL;
$$;

-- 1b. SCHEMA RELATIONSHIPS: Ensure Foreign Keys for Joined Counts
-- Supabase requires explicit foreign keys for nested .select('*, modules:course_modules(count)') to work.
DO $$ 
BEGIN
    -- Course Modules Relationship
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'course_modules_course_id_fkey') THEN
        ALTER TABLE public.course_modules 
        ADD CONSTRAINT course_modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
    END IF;

    -- Course Enrollments Relationship
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'course_enrollments_course_id_fkey') THEN
        ALTER TABLE public.course_enrollments 
        ADD CONSTRAINT course_enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 2. SCHEMA: Add missing columns to 'courses' table
-- We use IF NOT EXISTS to avoid errors if run multiple times
ALTER TABLE public.courses
ADD COLUMN IF NOT EXISTS academic_year text DEFAULT '2025-2026',
ADD COLUMN IF NOT EXISTS sections text[] DEFAULT '{}'::text[],
ADD COLUMN IF NOT EXISTS co_teacher_id uuid REFERENCES public.profiles(id),
ADD COLUMN IF NOT EXISTS guest_faculty text,
ADD COLUMN IF NOT EXISTS auto_enroll boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS max_capacity integer DEFAULT 30,
ADD COLUMN IF NOT EXISTS elective_rules text,
ADD COLUMN IF NOT EXISTS publish_date timestamptz,
ADD COLUMN IF NOT EXISTS auto_sync_timetable boolean DEFAULT true;

-- Ensure dependent tables exist
CREATE TABLE IF NOT EXISTS public.course_modules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
    title text NOT NULL,
    duration_hours numeric DEFAULT 0,
    order_index integer DEFAULT 0,
    status text DEFAULT 'Active',
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.course_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.profiles(id),
    action text NOT NULL,
    details jsonb,
    created_at timestamptz DEFAULT now()
);

-- 3. RLS: Enable and Configure
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_modules ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to ensure clean state
DROP POLICY IF EXISTS "Admins can manage courses in their branch" ON public.courses;
DROP POLICY IF EXISTS "Users can view courses in their branch" ON public.courses;
DROP POLICY IF EXISTS "Authenticated users can view courses" ON public.courses;
DROP POLICY IF EXISTS "Create courses" ON public.courses;
DROP POLICY IF EXISTS "Inherit course visibility" ON public.course_modules;

-- Policy: View (All authenticated users in the branch)
CREATE POLICY "Users can view courses in their branch" ON public.courses
FOR SELECT
USING (
    branch_id IN (SELECT public.get_my_branch_ids())
);

-- Policy: Manage (Admins/Principals/Coordinators)
CREATE POLICY "Admins can manage courses in their branch" ON public.courses
FOR ALL
USING (
    branch_id IN (SELECT public.get_my_branch_ids())
    AND (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() 
            AND role IN ('School Administration', 'Branch Admin', 'Super Admin', 'Academic Coordinator', 'Principal')
        )
        OR
        EXISTS (
            SELECT 1 FROM public.user_role_assignments
            WHERE user_id = auth.uid() AND branch_id = courses.branch_id
            AND role_name IN ('School Administration', 'Branch Admin', 'Academic Coordinator', 'Principal')
        )
    )
);

-- RLS for Modules (Inherit from Course)
CREATE POLICY "Inherit course visibility" ON public.course_modules
FOR ALL
USING (
    EXISTS (
        SELECT 1 FROM public.courses c
        WHERE c.id = course_modules.course_id
        AND c.branch_id IN (SELECT public.get_my_branch_ids())
    )
);

-- 4. RPC: create_course_with_modules (SINGLE CREATION)
-- Now handles ALL form fields
CREATE OR REPLACE FUNCTION public.create_course_with_modules(
    p_course_data jsonb,
    p_modules_data jsonb,
    p_branch_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_course_id bigint;
    v_module jsonb;
    v_order int := 1;
    v_teacher_id uuid;
    v_co_teacher_id uuid;
    v_credits numeric;
BEGIN
    -- 1. Validate Branch Access
    IF NOT EXISTS (
        SELECT 1 FROM public.school_branches 
        WHERE id = p_branch_id 
        AND id IN (SELECT public.get_my_branch_ids())
    ) THEN
        RAISE EXCEPTION 'Unauthorized: You do not have permission to create courses in this branch.';
    END IF;

    -- 2. Prepare Data
    v_teacher_id := NULLIF(p_course_data->>'teacher_id', '')::uuid;
    v_co_teacher_id := NULLIF(p_course_data->>'co_teacher_id', '')::uuid;
    v_credits := COALESCE((p_course_data->>'credits')::numeric, 3);

    -- 3. Insert Course
    INSERT INTO public.courses (
        title,
        code,
        description,
        credits,
        category,
        grade_level,
        status,
        teacher_id,
        department,
        subject_type,
        branch_id,
        academic_year,
        sections,
        co_teacher_id,
        guest_faculty,
        auto_enroll,
        max_capacity,
        elective_rules,
        publish_date,
        auto_sync_timetable,
        created_at
    ) VALUES (
        p_course_data->>'title',
        p_course_data->>'code',
        p_course_data->>'description',
        v_credits,
        p_course_data->>'category',
        p_course_data->>'grade_level',
        p_course_data->>'status',
        v_teacher_id,
        p_course_data->>'department',
        p_course_data->>'subject_type',
        p_branch_id,
        COALESCE(p_course_data->>'academic_year', '2025-2026'),
        -- Handle sections array from JSON
        ARRAY(SELECT jsonb_array_elements_text(COALESCE(p_course_data->'sections', '[]'::jsonb))),
        v_co_teacher_id,
        p_course_data->>'guest_faculty',
        COALESCE((p_course_data->>'auto_enroll')::boolean, true),
        COALESCE((p_course_data->>'max_capacity')::integer, 30),
        p_course_data->>'elective_rules',
        CASE WHEN (p_course_data->>'publish_date') = '' THEN NULL ELSE (p_course_data->>'publish_date')::timestamptz END,
        COALESCE((p_course_data->>'auto_sync_timetable')::boolean, true),
        now()
    )
    RETURNING id INTO v_course_id;

    -- 4. Insert Modules (if any)
    IF p_modules_data IS NOT NULL AND jsonb_array_length(p_modules_data) > 0 THEN
        FOR v_module IN SELECT * FROM jsonb_array_elements(p_modules_data)
        LOOP
            INSERT INTO public.course_modules (
                course_id,
                title,
                duration_hours,
                order_index,
                status
            ) VALUES (
                v_course_id,
                v_module->>'title',
                COALESCE((v_module->>'hours')::numeric, 0),
                v_order,
                'Active'
            );
            v_order := v_order + 1;
        END LOOP;
    END IF;

    -- 5. Log Action
    BEGIN
        INSERT INTO public.course_logs (course_id, user_id, action, details)
        VALUES (
            v_course_id,
            auth.uid(),
            'CREATED',
            jsonb_build_object('title', p_course_data->>'title', 'modules_count', v_order - 1)
        );
    EXCEPTION WHEN OTHERS THEN NULL; END;

    RETURN jsonb_build_object('id', v_course_id, 'success', true);
END;
$$;

-- 5. RPC: bulk_import_courses (BULK CREATION)
-- Updated to handle new fields
DROP FUNCTION IF EXISTS public.bulk_import_courses(jsonb);
DROP FUNCTION IF EXISTS public.bulk_import_courses(jsonb, bigint);

CREATE OR REPLACE FUNCTION public.bulk_import_courses(p_courses jsonb, p_branch_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    course_data jsonb;
    success_count int := 0;
    failure_count int := 0;
    errors jsonb[] := ARRAY[]::jsonb[];
    v_credits numeric;
BEGIN
    IF p_branch_id IS NULL THEN
        RAISE EXCEPTION 'Branch ID is required for course import';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.school_branches 
        WHERE id = p_branch_id 
        AND id IN (SELECT public.get_my_branch_ids())
    ) THEN
        RAISE EXCEPTION 'Unauthorized: You do not have access to this branch. Please verify your branch assignment.';
    END IF;

    FOR course_data IN SELECT * FROM jsonb_array_elements(p_courses)
    LOOP
        BEGIN
            v_credits := COALESCE(NULLIF(course_data->>'credits', '')::numeric, 3);
            
            INSERT INTO public.courses (
                title, 
                code, 
                grade_level, 
                description, 
                category, 
                credits, 
                status, 
                department,
                branch_id,
                academic_year,
                sections,
                max_capacity,
                auto_enroll,
                guest_faculty,
                created_at
            ) VALUES (
                course_data->>'title',
                course_data->>'code',
                course_data->>'grade_level',
                course_data->>'description',
                COALESCE(course_data->>'category', 'Core'),
                v_credits,
                'Active',
                course_data->>'department',
                p_branch_id,
                COALESCE(course_data->>'academic_year', '2025-2026'),
                -- Handle comma-separated sections from CSV
                string_to_array(NULLIF(course_data->>'sections', ''), ','),
                COALESCE(NULLIF(course_data->>'max_capacity', '')::integer, 30),
                -- Handle boolean text safely
                CASE WHEN lower(course_data->>'auto_enroll') = 'false' THEN false ELSE true END,
                course_data->>'guest_faculty',
                now()
            );
            success_count := success_count + 1;
        EXCEPTION WHEN OTHERS THEN
            failure_count := failure_count + 1;
            errors := array_append(errors, jsonb_build_object(
                'row_index', (course_data->>'row_index')::int,
                'title', course_data->>'title',
                'error', SQLERRM
            ));
        END;
    END LOOP;

    RETURN jsonb_build_object(
        'success_count', success_count,
        'failure_count', failure_count,
        'errors', to_jsonb(errors)
    );
END;
$$;

-- 6. Permissions
GRANT ALL ON public.courses TO authenticated;
GRANT ALL ON public.course_modules TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_branch_ids TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_course_with_modules TO authenticated;
GRANT EXECUTE ON FUNCTION public.bulk_import_courses TO authenticated;
