-- ===============================================================================================
--  GURUKUL OS - INSTITUTIONAL HIERARCHY & HANDSHAKE PROTOCOL (v4.0)
--  Generated by: Antigravity AI
--  Date: January 30, 2026
--  Description: Comprehensive School & Branch logic flow ensuring multi-tenant isolation.
--               Implements Strict Branch Visibility, Zero-Leakage RPCs, and Secure Handshake.
-- ===============================================================================================

BEGIN;

-- 1. SCHEMA ALIGNMENT
-- ===============================================================================================
DO $$ 
DECLARE
    t TEXT;
BEGIN
    -- Ensure Handshake Audit Logs Exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'handshake_audit_logs') THEN
        CREATE TABLE public.handshake_audit_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_id BIGINT,
            admin_user_id UUID,
            target_email TEXT,
            event_type TEXT, 
            details JSONB DEFAULT '{}',
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
    END IF;

    -- Ensure school_id/branch_id columns exist on all operational tables
    FOR t IN 
        SELECT unnest(ARRAY[
            'profiles', 'student_profiles', 'teacher_profiles', 'parent_profiles', 
            'staff_profiles', 'enquiries', 'admissions', 'fee_structures', 
            'fee_invoices', 'fee_payments', 'student_fee_accounts', 'expenses', 
            'notifications', 'attendance_records', 'timetables', 'assignments', 'submissions',
            'school_branches', 'tasks', 'audit_logs', 'communications'
        ])
    LOOP
        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t AND column_name = 'school_id') THEN
                EXECUTE format('ALTER TABLE public.%I ADD COLUMN school_id UUID', t);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t AND column_name = 'branch_id') 
               AND t NOT IN ('school_admin_profiles', 'school_branches') THEN
                EXECUTE format('ALTER TABLE public.%I ADD COLUMN branch_id BIGINT', t);
            END IF;
        END IF;
    END LOOP;
END $$;

-- 2. SECURITY HELPER FUNCTIONS
-- ===============================================================================================

CREATE OR REPLACE FUNCTION public.get_my_school_id() RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN RETURN (SELECT school_id FROM public.profiles WHERE id = auth.uid()); END; $$;

CREATE OR REPLACE FUNCTION public.get_my_branch_id() RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN RETURN (SELECT branch_id FROM public.profiles WHERE id = auth.uid()); END; $$;

CREATE OR REPLACE FUNCTION public.is_super_admin() RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN RETURN EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'Super Admin'); END; $$;

-- Helper: VIEW ACCESS (Read-Only from Master Support)
CREATE OR REPLACE FUNCTION public.has_institutional_access(p_school_id UUID, p_branch_id BIGINT DEFAULT NULL)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_role TEXT;
    v_my_school UUID;
    v_my_branch BIGINT;
BEGIN
    IF public.is_super_admin() THEN RETURN TRUE; END IF;
    SELECT role, school_id, branch_id INTO v_role, v_my_school, v_my_branch FROM public.profiles WHERE id = auth.uid();

    -- School Admin: Must match school_id
    IF v_role IN ('School Admin', 'School Administration') THEN
        RETURN v_my_school = p_school_id;
    END IF;

    -- Branch Admin / Staff / Student: Match School ID AND (Match Branch OR Global Record)
    IF v_my_school = p_school_id THEN
        IF p_branch_id IS NULL OR v_my_branch = p_branch_id THEN
            RETURN TRUE;
        END IF;
    END IF;
    RETURN FALSE;
END;
$$;

-- Helper: WRITE ACCESS (Strict Isolation)
CREATE OR REPLACE FUNCTION public.has_institutional_write_access(p_school_id UUID, p_branch_id BIGINT DEFAULT NULL)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_role TEXT;
    v_my_school UUID;
    v_my_branch BIGINT;
BEGIN
    IF public.is_super_admin() THEN RETURN TRUE; END IF;
    SELECT role, school_id, branch_id INTO v_role, v_my_school, v_my_branch FROM public.profiles WHERE id = auth.uid();
    
    -- School Admin: Full Write
    IF v_role IN ('School Admin', 'School Administration') THEN
        RETURN v_my_school = p_school_id;
    END IF;
    
    -- Branch Admin: Write ONLY to Own Branch
    IF v_my_school = p_school_id AND p_branch_id IS NOT NULL AND v_my_branch = p_branch_id THEN
        RETURN TRUE;
    END IF;
    
    RETURN FALSE;
END;
$$;

-- 3. STRICT VISIBILITY RPCs (The Core Fix)
-- ===============================================================================================

-- RPC: Get School Branches (STRICTLY FILTERED)
DROP FUNCTION IF EXISTS public.get_school_branches() CASCADE;
CREATE OR REPLACE FUNCTION public.get_school_branches()
RETURNS SETOF public.school_branches LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_user_role TEXT;
    v_my_school_id UUID;
    v_my_branch_id BIGINT;
    v_user_email TEXT;
BEGIN
    SELECT role, school_id, branch_id INTO v_user_role, v_my_school_id, v_my_branch_id 
    FROM public.profiles WHERE id = auth.uid();
    
    v_user_email := auth.jwt() ->> 'email';

    -- Case 1: Super Admin (See All)
    IF v_user_role = 'Super Admin' THEN
        RETURN QUERY SELECT * FROM public.school_branches ORDER BY name;
        RETURN;
    END IF;

    -- Case 2: School Admin (See All in School)
    IF v_user_role IN ('School Admin', 'School Administration') AND v_my_branch_id IS NULL THEN
        -- He is a centralized admin
        RETURN QUERY SELECT * FROM public.school_branches 
        WHERE school_id = v_my_school_id
        ORDER BY is_main_branch DESC, name;
        RETURN;
    END IF;

    -- Case 3: Branch Admin / Staff (See ONLY Own Branch)
    -- Also include "Target Identity" match for Handshake Phase (Email match)
    RETURN QUERY SELECT * FROM public.school_branches 
    WHERE id = v_my_branch_id 
       OR LOWER(admin_email) = LOWER(v_user_email);
END;
$$;

-- RPC: Get Network Registry Metrics (STRICTLY FILTERED)
DROP FUNCTION IF EXISTS public.get_network_registry_metrics() CASCADE;
CREATE OR REPLACE FUNCTION public.get_network_registry_metrics()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_role TEXT;
    v_school_id UUID;
    v_branch_id BIGINT;
    v_total_nodes INT;
    v_verified_links INT;
    v_online_nodes INT;
BEGIN
    SELECT role, school_id, branch_id INTO v_role, v_school_id, v_branch_id FROM public.profiles WHERE id = auth.uid();

    -- Filter base table
    IF v_role IN ('School Admin', 'School Administration') AND v_branch_id IS NULL THEN
        -- School View: All Nodes
        SELECT count(*), count(*) FILTER (WHERE status = 'Verified'), count(*) FILTER (WHERE status = 'Online')
        INTO v_total_nodes, v_verified_links, v_online_nodes
        FROM public.school_branches
        WHERE school_id = v_school_id;
    ELSE
        -- Branch View: Only Self
        SELECT count(*), count(*) FILTER (WHERE status = 'Verified'), count(*) FILTER (WHERE status = 'Online')
        INTO v_total_nodes, v_verified_links, v_online_nodes
        FROM public.school_branches
        WHERE id = v_branch_id;
    END IF;

    RETURN jsonb_build_object(
        'total_nodes', COALESCE(v_total_nodes, 0),
        'verified_links', COALESCE(v_verified_links, 0),
        'online_nodes', COALESCE(v_online_nodes, 0),
        'protocol_health', 100,
        'version', 'v4.5'
    );
END;
$$;

-- RPC: Auto Handshake On Login (Identity Resolver)
DROP FUNCTION IF EXISTS public.auto_handshake_on_login() CASCADE;
CREATE OR REPLACE FUNCTION public.auto_handshake_on_login()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_user_email TEXT;
    v_branch RECORD;
BEGIN
    v_user_email := auth.jwt() ->> 'email';

    -- Check if this user is designated as a Branch Admin via Email Match
    SELECT * INTO v_branch 
    FROM public.school_branches 
    WHERE LOWER(admin_email) = LOWER(v_user_email)
    AND (admin_user_id IS NULL OR admin_user_id = auth.uid());

    IF v_branch.id IS NOT NULL THEN
        -- Auto-Link logic
        UPDATE public.school_branches 
        SET admin_user_id = auth.uid(), status = 'Online', updated_at = NOW() 
        WHERE id = v_branch.id;
        
        -- Update Profile
        UPDATE public.profiles
        SET branch_id = v_branch.id,
            school_id = v_branch.school_id, -- Inherit School ID
            role = 'School Administration' -- Branch Admins share this role name but are scoped by branch_id
        WHERE id = auth.uid();

        -- Audit
        INSERT INTO public.handshake_audit_logs (branch_id, admin_user_id, target_email, event_type)
        VALUES (v_branch.id, auth.uid(), v_user_email, 'AUTO_HANDSHAKE');

        RETURN jsonb_build_object('success', true, 'branch_id', v_branch.id, 'mode', 'AUTO_LINK');
    END IF;

    RETURN jsonb_build_object('success', false, 'message', 'No pending branch assignment found.');
END;
$$;

-- 4. DYNAMIC RLS ENFORCEMENT
-- ===============================================================================================

DO $$ 
DECLARE
    t TEXT;
    has_branch BOOLEAN;
BEGIN
    -- Force Enable RLS
    FOR t IN 
        SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' 
        AND table_name IN ('school_branches') -- Ensure Registry is locked
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;

    -- Policy: Branch Registry (Strict)
    DROP POLICY IF EXISTS "Branch Registry Policy" ON public.school_branches;
    CREATE POLICY "Branch Registry Policy" ON public.school_branches FOR ALL USING (
        -- School Admin
        (school_id = public.get_my_school_id() AND public.get_my_branch_id() IS NULL)
        OR 
        -- Branch Admin (Own Branch)
        id = public.get_my_branch_id()
        OR 
        -- Handshake Candidate (Based on Email)
        LOWER(admin_email) = LOWER(auth.jwt() ->> 'email')
    );

    -- Apply policies to all other tables
    FOR t IN 
        SELECT DISTINCT table_name 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND column_name = 'school_id'
        AND table_name NOT IN ('profiles', 'school_branches')
    LOOP
        SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t AND column_name = 'branch_id') INTO has_branch;

        EXECUTE format('DROP POLICY IF EXISTS "Hierarchal View" ON public.%I', t);
        EXECUTE format('DROP POLICY IF EXISTS "Hierarchal Modify" ON public.%I', t);
        
        IF has_branch THEN
            EXECUTE format('CREATE POLICY "Hierarchal View" ON public.%I FOR SELECT USING (public.has_institutional_access(school_id, branch_id))', t);
            EXECUTE format('CREATE POLICY "Hierarchal Modify" ON public.%I FOR ALL USING (public.has_institutional_write_access(school_id, branch_id)) WITH CHECK (public.has_institutional_write_access(school_id, branch_id))', t);
        ELSE
            EXECUTE format('CREATE POLICY "Hierarchal Access" ON public.%I FOR ALL USING (public.has_institutional_access(school_id, NULL))', t);
        END IF;
    END LOOP;
END $$;

-- 5. TRIGGER: INHERIT LINEAGE
-- ===============================================================================================

CREATE OR REPLACE FUNCTION public.trigger_inherit_lineage()
RETURNS TRIGGER AS $$
DECLARE
    v_my_school UUID;
    v_my_branch BIGINT;
BEGIN
    SELECT school_id, branch_id INTO v_my_school, v_my_branch FROM public.profiles WHERE id = auth.uid();
    IF NEW.school_id IS NULL THEN NEW.school_id := v_my_school; END IF;
    IF NEW.branch_id IS NULL AND v_my_branch IS NOT NULL THEN NEW.branch_id := v_my_branch; END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Attach Trigger to all tables
DO $$ 
DECLARE t TEXT;
BEGIN
    FOR t IN 
        SELECT DISTINCT table_name FROM information_schema.columns 
        WHERE table_schema = 'public' AND column_name = 'school_id' 
        AND table_name NOT IN ('profiles', 'school_branches', 'handshake_audit_logs')
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_inherit_lineage ON public.%I', t);
        EXECUTE format('CREATE TRIGGER trg_inherit_lineage BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.trigger_inherit_lineage()', t);
    END LOOP;
END $$;

COMMIT;
