-- ===============================================================================================
--  GURUKUL OS - INSTITUTIONAL HIERARCHY & HANDSHAKE PROTOCOL (v4.0)
--  Generated by: Antigravity AI
--  Date: January 30, 2026
--  Description: Comprehensive School & Branch logic flow ensuring multi-tenant isolation.
--               Implements Strict Branch Visibility, Zero-Leakage RPCs, and Secure Handshake.
-- ===============================================================================================

BEGIN;

-- 1. SCHEMA ALIGNMENT
-- ===============================================================================================
DO $$ 
DECLARE
    t TEXT;
BEGIN
    -- Ensure Handshake Audit Logs Exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'handshake_audit_logs') THEN
        CREATE TABLE public.handshake_audit_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_id BIGINT,
            admin_user_id UUID,
            target_email TEXT,
            event_type TEXT, 
            details JSONB DEFAULT '{}',
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
    END IF;

    -- Ensure school_id/branch_id columns exist on all operational tables
    FOR t IN 
        SELECT unnest(ARRAY[
            'profiles', 'student_profiles', 'teacher_profiles', 'parent_profiles', 
            'staff_profiles', 'enquiries', 'admissions', 'fee_structures', 
            'fee_invoices', 'fee_payments', 'student_fee_accounts', 'expenses', 
            'notifications', 'attendance_records', 'timetables', 'assignments', 'submissions',
            'school_branches', 'tasks', 'audit_logs', 'communications'
        ])
    LOOP
        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t AND column_name = 'school_id') THEN
                EXECUTE format('ALTER TABLE public.%I ADD COLUMN school_id UUID', t);
            END IF;
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t AND column_name = 'branch_id') 
               AND t NOT IN ('school_admin_profiles', 'school_branches') THEN
                EXECUTE format('ALTER TABLE public.%I ADD COLUMN branch_id BIGINT', t);
            END IF;
        END IF;
    END LOOP;
END $$;

-- 2. SECURITY HELPER FUNCTIONS
-- ===============================================================================================

CREATE OR REPLACE FUNCTION public.get_my_school_id() RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN RETURN (SELECT school_id FROM public.profiles WHERE id = auth.uid()); END; $$;

CREATE OR REPLACE FUNCTION public.get_my_branch_id() RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN RETURN (SELECT branch_id FROM public.profiles WHERE id = auth.uid()); END; $$;

CREATE OR REPLACE FUNCTION public.is_super_admin() RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN RETURN EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'Super Admin'); END; $$;

CREATE OR REPLACE FUNCTION public.is_head_office_admin() RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_role TEXT;
    v_branch_id BIGINT;
    v_is_main BOOLEAN;
BEGIN
    SELECT role, branch_id INTO v_role, v_branch_id FROM public.profiles WHERE id = auth.uid();
    
    -- Case 1: Super Admin is always Head Office
    IF v_role = 'Super Admin' THEN RETURN TRUE; END IF;
    
    -- Case 2: School Admin with no branch_id is Centralized Owner
    IF v_role IN ('School Admin', 'School Administration') AND v_branch_id IS NULL THEN RETURN TRUE; END IF;
    
    -- Case 3: Explicitly assigned to Main Branch
    IF v_branch_id IS NOT NULL THEN
        SELECT is_main_branch INTO v_is_main FROM public.school_branches WHERE id = v_branch_id;
        IF v_is_main THEN RETURN TRUE; END IF;
    END IF;
    
    RETURN FALSE;
END; $$;

-- HANDSHAKE: Verify Branch Access Key (Enhanced for Redundancy)
CREATE OR REPLACE FUNCTION public.verify_branch_execution_node(
    p_access_key TEXT,
    p_admin_email TEXT
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_branch RECORD;
    v_clean_key TEXT;
BEGIN
    -- 1. Sanitation: Canonical format XXXX-XXXX (Uppercase, no spaces)
    v_clean_key := UPPER(TRIM(p_access_key));
    
    -- Handle cases where user might have omitted the hyphen 
    IF LENGTH(v_clean_key) = 8 AND v_clean_key NOT LIKE '%-%' THEN
        v_clean_key := SUBSTR(v_clean_key, 1, 4) || '-' || SUBSTR(v_clean_key, 5, 4);
    END IF;

    -- 2. Validate against Registry (Case Insensitive for Email)
    SELECT * INTO v_branch
    FROM public.school_branches
    WHERE UPPER(access_key) = v_clean_key 
    AND (admin_email ILIKE p_admin_email OR p_admin_email IS NULL);

    IF v_branch.id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Identity Verification Failed: Invalid Access Key or Email Mismatch.');
    END IF;

    -- 3. Success
    RETURN jsonb_build_object(
        'success', true, 
        'branch_id', v_branch.id, 
        'school_id', v_branch.school_id,
        'branch_name', v_branch.name,
        'admin_email', v_branch.admin_email
    );
END;
$$;

-- Helper: VIEW ACCESS (v4.0 Strict Isolation)
CREATE OR REPLACE FUNCTION public.has_institutional_access(p_school_id UUID, p_branch_id BIGINT DEFAULT NULL)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_is_ho BOOLEAN;
    v_my_school UUID;
    v_my_branch BIGINT;
BEGIN
    IF public.is_super_admin() THEN RETURN TRUE; END IF;
    
    v_is_ho := public.is_head_office_admin();
    v_my_school := public.get_my_school_id();
    v_my_branch := public.get_my_branch_id();

    -- Rule 1: School ID must match (Zero-Leakage)
    IF v_my_school IS NULL OR v_my_school != p_school_id THEN RETURN FALSE; END IF;

    -- Rule 2: HO Admin can see all branches in institutional network
    IF v_is_ho THEN RETURN TRUE; END IF;

    -- Rule 3: Branch Level can only see records for their branch OR global institution records
    IF p_branch_id IS NULL OR v_my_branch = p_branch_id THEN
        RETURN TRUE;
    END IF;

    RETURN FALSE;
END;
$$;

-- Helper: WRITE ACCESS (v4.0 Strict Isolation)
CREATE OR REPLACE FUNCTION public.has_institutional_write_access(p_school_id UUID, p_branch_id BIGINT DEFAULT NULL)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_is_ho BOOLEAN;
    v_my_school UUID;
    v_my_branch BIGINT;
BEGIN
    IF public.is_super_admin() THEN RETURN TRUE; END IF;
    
    v_is_ho := public.is_head_office_admin();
    v_my_school := public.get_my_school_id();
    v_my_branch := public.get_my_branch_id();

    -- Rule 1: School ID must match
    IF v_my_school IS NULL OR v_my_school != p_school_id THEN RETURN FALSE; END IF;

    -- Rule 2: HO Admin has full write access
    IF v_is_ho THEN RETURN TRUE; END IF;

    -- Rule 3: Branch Level can ONLY write to their specific branch
    IF p_branch_id IS NOT NULL AND v_my_branch = p_branch_id THEN
        RETURN TRUE;
    END IF;

    RETURN FALSE;
END;
$$;

-- 3. STRICT VISIBILITY RPCs (The Core Fix)
-- ===============================================================================================

-- RPC: Get School Branches (STRICTLY FILTERED v5.0)
DROP FUNCTION IF EXISTS public.get_school_branches() CASCADE;
CREATE OR REPLACE FUNCTION public.get_school_branches()
RETURNS SETOF public.school_branches LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_is_ho BOOLEAN;
    v_my_school_id UUID;
    v_my_branch_id BIGINT;
    v_user_email TEXT;
BEGIN
    v_is_ho := public.is_head_office_admin();
    v_my_school_id := public.get_my_school_id();
    v_my_branch_id := public.get_my_branch_id();
    v_user_email := auth.jwt() ->> 'email';

    -- Case 1: Head Office / Super Admin (Can view entire network)
    IF v_is_ho THEN
        RETURN QUERY SELECT * FROM public.school_branches 
        WHERE school_id = v_my_school_id OR public.is_super_admin()
        ORDER BY is_main_branch DESC, name;
        RETURN;
    END IF;

    -- Case 2: Branch Level (Restricted to assigned branch only)
    RETURN QUERY SELECT * FROM public.school_branches 
    WHERE id = v_my_branch_id 
       OR LOWER(admin_email) = LOWER(v_user_email);
END;
$$;

-- RPC: Get Network Registry Metrics (STRICTLY FILTERED - Desync Proof)
DROP FUNCTION IF EXISTS public.get_network_registry_metrics() CASCADE;
CREATE OR REPLACE FUNCTION public.get_network_registry_metrics()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_role TEXT;
    v_school_id UUID;
    v_branch_id BIGINT;
    v_total_nodes INT;
    v_verified_links INT;
    v_online_nodes INT;
BEGIN
    BEGIN
        SELECT role, school_id, branch_id INTO v_role, v_school_id, v_branch_id FROM public.profiles WHERE id = auth.uid();
    EXCEPTION WHEN undefined_column THEN
        SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
        v_school_id := NULL; v_branch_id := NULL;
    END;

    -- Fallback: If school_id is missing in profile, try to find it in school_admin_profiles
    IF v_school_id IS NULL AND v_role IN ('School Admin', 'School Administration') THEN
        BEGIN
            SELECT user_id INTO v_school_id FROM public.school_admin_profiles WHERE user_id = auth.uid();
        EXCEPTION WHEN OTHERS THEN v_school_id := NULL; END;
    END IF;

    -- Filter base table (v2.0 with HO logic)
    IF public.is_head_office_admin() THEN
        -- School View: All Nodes
        SELECT count(*), count(*) FILTER (WHERE status = 'Verified' OR status = 'Active'), count(*) FILTER (WHERE status = 'Online')
        INTO v_total_nodes, v_verified_links, v_online_nodes
        FROM public.school_branches
        WHERE school_id = public.get_my_school_id() OR public.is_super_admin();
    ELSE
        -- Branch View: Only Self
        SELECT count(*), count(*) FILTER (WHERE status = 'Verified' OR status = 'Active'), count(*) FILTER (WHERE status = 'Online')
        INTO v_total_nodes, v_verified_links, v_online_nodes
        FROM public.school_branches
        WHERE id = public.get_my_branch_id();
    END IF;

    RETURN jsonb_build_object(
        'total_nodes', COALESCE(v_total_nodes, 0),
        'verified_links', COALESCE(v_verified_links, 0),
        'online_nodes', COALESCE(v_online_nodes, 0),
        'protocol_health', 100,
        'version', 'v4.5-resilient'
    );
END;
$$;

-- RPC: Auto Handshake On Login (Identity Resolver v2.0)
DROP FUNCTION IF EXISTS public.auto_handshake_on_login() CASCADE;
CREATE OR REPLACE FUNCTION public.auto_handshake_on_login()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_user_email TEXT;
    v_branch RECORD;
BEGIN
    v_user_email := auth.jwt() ->> 'email';
    
    IF v_user_email IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'No session context found.');
    END IF;

    -- Check if this user is designated as a Branch Admin via Email Match
    SELECT * INTO v_branch 
    FROM public.school_branches 
    WHERE LOWER(admin_email) = LOWER(v_user_email)
    AND (admin_user_id IS NULL OR admin_user_id = auth.uid())
    LIMIT 1;

    IF v_branch.id IS NOT NULL THEN
        -- Auto-Link logic (Claiming the node)
        UPDATE public.school_branches 
        SET admin_user_id = auth.uid(), status = 'Online', updated_at = NOW() 
        WHERE id = v_branch.id;
        
        -- Propagate Identity to Profile
        UPDATE public.profiles
        SET branch_id = v_branch.id,
            school_id = v_branch.school_id,
            role = 'Branch Admin',
            profile_completed = true
        WHERE id = auth.uid();

        -- Audit
        INSERT INTO public.handshake_audit_logs (branch_id, admin_user_id, target_email, event_type, details)
        VALUES (v_branch.id, auth.uid(), v_user_email, 'AUTO_HANDSHAKE', jsonb_build_object('branch_name', v_branch.name));

        RETURN jsonb_build_object('success', true, 'branch_id', v_branch.id, 'mode', 'AUTO_LINK', 'branch_name', v_branch.name);
    END IF;

    RETURN jsonb_build_object('success', false, 'message', 'No pending branch assignment found.');
END;
$$;

-- RPC: Verify and Link Branch Admin (Manual Handshake)
DROP FUNCTION IF EXISTS public.verify_and_link_branch_admin(TEXT) CASCADE;
CREATE OR REPLACE FUNCTION public.verify_and_link_branch_admin(p_invitation_code TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_branch RECORD;
    v_user_id UUID := auth.uid();
    v_user_email TEXT := auth.jwt() ->> 'email';
    v_clean_key TEXT;
BEGIN
    -- 1. Sanitation
    v_clean_key := UPPER(TRIM(p_invitation_code));
    IF LENGTH(v_clean_key) = 8 AND v_clean_key NOT LIKE '%-%' THEN
        v_clean_key := SUBSTR(v_clean_key, 1, 4) || '-' || SUBSTR(v_clean_key, 5, 4);
    END IF;

    -- 2. Find the branch by Access Key (Verify Email if registered)
    SELECT * INTO v_branch 
    FROM public.school_branches 
    WHERE UPPER(access_key) = v_clean_key;

    IF v_branch.id IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Security Violation: Invalid Handshake Key.');
    END IF;

    -- 3. Identity Check (If admin_email was specified, must match current user)
    IF v_branch.admin_email IS NOT NULL AND LOWER(v_branch.admin_email) != LOWER(v_user_email) THEN
        RETURN jsonb_build_object('success', false, 'message', 'Identity Mismatch: This key is reserved for ' || v_branch.admin_email);
    END IF;

    -- 4. Check if already claimed
    IF v_branch.admin_user_id IS NOT NULL AND v_branch.admin_user_id != v_user_id THEN
         RETURN jsonb_build_object('success', false, 'message', 'Registry Conflict: Node already claimed by another administrator.');
    END IF;

    -- 5. Link User to Branch
    UPDATE public.school_branches 
    SET admin_user_id = v_user_id, status = 'Online', updated_at = NOW() 
    WHERE id = v_branch.id;

    -- 6. Update Profile
    UPDATE public.profiles
    SET branch_id = v_branch.id,
        school_id = v_branch.school_id,
        role = 'Branch Admin',
        profile_completed = true
    WHERE id = v_user_id;

    -- 7. Ensure specialized profile exists
    INSERT INTO public.school_admin_profiles (user_id, onboarding_step)
    VALUES (v_user_id, 'completed')
    ON CONFLICT (user_id) DO UPDATE SET onboarding_step = 'completed';
    
    -- 8. Log Handshake
    INSERT INTO public.handshake_audit_logs (branch_id, admin_user_id, target_email, event_type)
    VALUES (v_branch.id, v_user_id, v_user_email, 'MANUAL_HANDSHAKE_VERIFY');

    RETURN jsonb_build_object('success', true, 'branch_id', v_branch.id, 'branch_name', v_branch.name);
END;
$$;

-- RPC: Get All Users for Admin (STRICT BRANCH FILTERING)
DROP FUNCTION IF EXISTS public.get_all_users_for_admin() CASCADE;
CREATE OR REPLACE FUNCTION public.get_all_users_for_admin()
RETURNS SETOF public.profiles LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_is_ho BOOLEAN;
    v_my_school_id UUID;
    v_my_branch_id BIGINT;
BEGIN
    v_is_ho := public.is_head_office_admin();
    v_my_school_id := public.get_my_school_id();
    v_my_branch_id := public.get_my_branch_id();

    IF v_is_ho THEN
        -- HO can see all users in the institutional network
        RETURN QUERY SELECT * FROM public.profiles WHERE school_id = v_my_school_id OR public.is_super_admin();
    ELSE
        -- Branch Admin is LOCKED to seeing only their branch directory
        RETURN QUERY SELECT * FROM public.profiles WHERE branch_id = v_my_branch_id;
    END IF;
END;
$$;

-- 4. DYNAMIC RLS ENFORCEMENT
-- ===============================================================================================

DO $$ 
DECLARE
    t TEXT;
    has_branch BOOLEAN;
BEGIN
    -- Force Enable RLS
    FOR t IN 
        SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' 
        AND table_name IN ('school_branches') -- Ensure Registry is locked
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;

    -- Policy: Profiles (Self & Chain of Command)
    DROP POLICY IF EXISTS "Profile Discovery Policy" ON public.profiles;
    CREATE POLICY "Profile Discovery Policy" ON public.profiles FOR ALL USING (
        id = auth.uid() 
        OR public.is_super_admin()
        OR (school_id = public.get_my_school_id() AND public.is_head_office_admin())
        OR (branch_id = public.get_my_branch_id() AND public.get_my_branch_id() IS NOT NULL)
    );

    -- Apply policies to all other tables
    FOR t IN 
        SELECT DISTINCT table_name 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND column_name = 'school_id'
        AND table_name NOT IN ('profiles', 'school_branches')
    LOOP
        SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t AND column_name = 'branch_id') INTO has_branch;

        EXECUTE format('DROP POLICY IF EXISTS "Hierarchal View" ON public.%I', t);
        EXECUTE format('DROP POLICY IF EXISTS "Hierarchal Modify" ON public.%I', t);
        
        IF has_branch THEN
            EXECUTE format('CREATE POLICY "Hierarchal View" ON public.%I FOR SELECT USING (public.has_institutional_access(school_id, branch_id))', t);
            EXECUTE format('CREATE POLICY "Hierarchal Modify" ON public.%I FOR ALL USING (public.has_institutional_write_access(school_id, branch_id)) WITH CHECK (public.has_institutional_write_access(school_id, branch_id))', t);
        ELSE
            EXECUTE format('CREATE POLICY "Hierarchal Access" ON public.%I FOR ALL USING (public.has_institutional_access(school_id, NULL))', t);
        END IF;
    END LOOP;
END $$;

-- 5. TRIGGER: INHERIT LINEAGE
-- ===============================================================================================

CREATE OR REPLACE FUNCTION public.trigger_inherit_lineage()
RETURNS TRIGGER AS $$
DECLARE
    v_my_school UUID;
    v_my_branch BIGINT;
BEGIN
    SELECT school_id, branch_id INTO v_my_school, v_my_branch FROM public.profiles WHERE id = auth.uid();
    IF NEW.school_id IS NULL THEN NEW.school_id := v_my_school; END IF;
    IF NEW.branch_id IS NULL AND v_my_branch IS NOT NULL THEN NEW.branch_id := v_my_branch; END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Attach Trigger to all tables
DO $$ 
DECLARE t TEXT;
BEGIN
    FOR t IN 
        SELECT DISTINCT table_name FROM information_schema.columns 
        WHERE table_schema = 'public' AND column_name = 'school_id' 
        AND table_name NOT IN ('profiles', 'school_branches', 'handshake_audit_logs')
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_inherit_lineage ON public.%I', t);
        EXECUTE format('CREATE TRIGGER trg_inherit_lineage BEFORE INSERT ON public.%I FOR EACH ROW EXECUTE FUNCTION public.trigger_inherit_lineage()', t);
    END LOOP;
END $$;

COMMIT;
