-- ===============================================================================================
--  GURUKUL OS - INSTITUTIONAL HIERARCHY & HANDSHAKE PROTOCOL (v2.0)
--  Generated by: Antigravity AI
--  Date: January 29, 2026
--  Description: Comprehensive School & Branch logic flow ensuring multi-tenant isolation,
--               secure handshake validation, and cross-branch data leakage prevention.
-- ===============================================================================================

BEGIN;

-- 1. SCHEMA ALIGNMENT: ENSURE HIERARCHAL COLUMNS EXIST
-- ===============================================================================================

DO $$ 
DECLARE
    t TEXT;
BEGIN
    -- Add school_id to tables if missing
    FOR t IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE'
        AND table_name IN (
            'profiles', 'student_profiles', 'teacher_profiles', 'parent_profiles', 
            'staff_profiles', 'enquiries', 'admissions', 'fee_structures', 
            'fee_invoices', 'fee_payments', 'student_fee_accounts', 'expenses', 
            'notifications', 'attendance_records', 'timetables', 'assignments', 'submissions'
        )
    LOOP
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t AND column_name = 'school_id') THEN
            EXECUTE format('ALTER TABLE public.%I ADD COLUMN school_id UUID', t);
        END IF;
    END LOOP;
END $$;

-- 2. SECURITY HELPER FUNCTIONS (CONTEXT-AWARE)
-- ===============================================================================================

-- Helper: Get user's active school context
CREATE OR REPLACE FUNCTION public.get_my_school_id()
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN (SELECT school_id FROM public.profiles WHERE id = auth.uid());
END;
$$;

-- Helper: Get user's active branch context
CREATE OR REPLACE FUNCTION public.get_my_branch_id()
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN (SELECT branch_id FROM public.profiles WHERE id = auth.uid());
END;
$$;

-- Helper: Check if user is a Super Admin
CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'Super Admin');
END;
$$;

-- Helper: Check if user has context authority
CREATE OR REPLACE FUNCTION public.has_institutional_access(p_school_id UUID, p_branch_id BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_role TEXT;
    v_my_school UUID;
    v_my_branch BIGINT;
BEGIN
    -- Super Admins bypassing standard isolation
    IF public.is_super_admin() THEN RETURN TRUE; END IF;

    SELECT role, school_id, branch_id INTO v_role, v_my_school, v_my_branch FROM public.profiles WHERE id = auth.uid();

    -- School Admin (Head Office) access: Must match school_id
    IF v_role IN ('School Admin', 'School Administration') THEN
        RETURN v_my_school = p_school_id;
    END IF;

    -- Branch Admin / Staff / Student / Teacher: Must match both school and branch
    IF v_role IN ('Branch Admin', 'Teacher', 'Student', 'Parent/Guardian') THEN
        RETURN v_my_school = p_school_id AND v_my_branch = p_branch_id;
    END IF;

    RETURN FALSE;
END;
$$;

-- 3. CORE HANDSHAKE & ONBOARDING LOGIC
-- ===============================================================================================

-- RPC: Verify and Link Branch Admin (Handshake Gateway v3.5)
CREATE OR REPLACE FUNCTION public.verify_and_link_branch_admin(p_invitation_code TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_branch RECORD;
    v_user_email TEXT;
    v_clean_code TEXT;
BEGIN
    v_clean_code := UPPER(REGEXP_REPLACE(p_invitation_code, '[^A-Z0-9]', '', 'g'));
    v_user_email := auth.jwt() ->> 'email';

    -- 1. Locate Registry Entry
    SELECT * INTO v_branch FROM public.school_branches 
    WHERE UPPER(REGEXP_REPLACE(access_key, '[^A-Z0-9]', '', 'g')) = v_clean_code;

    IF v_branch.id IS NULL THEN
        INSERT INTO public.handshake_audit_logs (target_email, event_type, details)
        VALUES (v_user_email, 'HANDSHAKE_FAILURE', jsonb_build_object('reason', 'INVALID_KEY', 'code', p_invitation_code));
        RETURN jsonb_build_object('success', false, 'message', 'Node Discovery Failed: Access Key not found.');
    END IF;

    -- 2. Identity Verification (Email Match)
    IF LOWER(v_branch.admin_email) != LOWER(v_user_email) THEN
        INSERT INTO public.handshake_audit_logs (branch_id, target_email, event_type, details)
        VALUES (v_branch.id, v_user_email, 'IDENTITY_MISMATCH', jsonb_build_object('expected', v_branch.admin_email));
        RETURN jsonb_build_object('success', false, 'message', 'Identity Mismatch: This node is restricted to ' || v_branch.admin_email);
    END IF;

    -- 3. Atomic Handshake Execution
    UPDATE public.school_branches SET 
        status = 'Verified',
        admin_user_id = auth.uid(),
        updated_at = NOW()
    WHERE id = v_branch.id;

    -- Provision Profile with full lineage
    UPDATE public.profiles SET
        school_id = v_branch.school_id,
        branch_id = v_branch.id,
        role = 'School Administration',
        profile_completed = true
    WHERE id = auth.uid();

    -- Log Successful Handshake
    INSERT INTO public.handshake_audit_logs (branch_id, admin_user_id, target_email, event_type)
    VALUES (v_branch.id, auth.uid(), v_user_email, 'HANDSHAKE_SUCCESS');

    RETURN jsonb_build_object(
        'success', true, 
        'branch_id', v_branch.id, 
        'school_id', v_branch.school_id,
        'message', 'Handshake Secured. Node ' || v_branch.name || ' is now Online.'
    );
END;
$$;

-- 4. DYNAMIC RLS ENFORCEMENT (ZERO LEAKAGE LAYER)
-- ===============================================================================================

-- Enable RLS on all operational tables
DO $$ 
DECLARE
    t TEXT;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name IN (
            'profiles', 'school_branches', 'school_departments', 'school_classes', 
            'student_profiles', 'teacher_profiles', 'parent_profiles', 'enquiries', 
            'admissions', 'fee_structures', 'fee_invoices', 'fee_payments', 'expenses'
        )
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;
END $$;

-- Policy: Strict Institutional Isolation
-- School Admin sees all children of school. Branch Admin sees only their branch.
DROP POLICY IF EXISTS "Global Isolation Policy" ON public.profiles;
CREATE POLICY "Global Isolation Policy" ON public.profiles FOR ALL USING (
    id = auth.uid() OR public.has_institutional_access(school_id, branch_id)
);

DROP POLICY IF EXISTS "Branch Registry Policy" ON public.school_branches;
CREATE POLICY "Branch Registry Policy" ON public.school_branches FOR ALL USING (
    school_id = auth.uid() OR id = public.get_my_branch_id()
);

-- Apply Dynamic Branch Isolation to tables with both school_id and branch_id
DO $$ 
DECLARE
    t TEXT;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND column_name = 'branch_id'
        AND table_name NOT IN ('profiles', 'school_branches')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Hierarchal Access" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Hierarchal Access" ON public.%I FOR ALL USING (public.has_institutional_access(school_id, branch_id))', t);
    END LOOP;
END $$;

-- 5. AUTO-SYNC & TELEMETRY
-- ===============================================================================================

-- RPC: Get Institutional Context (For UI Handlers)
CREATE OR REPLACE FUNCTION public.get_institutional_context()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
    v_profile RECORD;
    v_branch RECORD;
BEGIN
    SELECT * INTO v_profile FROM public.profiles WHERE id = auth.uid();
    
    IF v_profile.branch_id IS NOT NULL THEN
        SELECT * INTO v_branch FROM public.school_branches WHERE id = v_profile.branch_id;
    END IF;

    RETURN jsonb_build_object(
        'user_id', auth.uid(),
        'role', v_profile.role,
        'school_id', v_profile.school_id,
        'branch_id', v_profile.branch_id,
        'branch_status', v_branch.status,
        'handshake_verified', (v_branch.status = 'Verified'),
        'server_time', NOW()
    );
END;
$$;

-- 6. TRIGGER: INHERIT SCHOOL ID ON CREATION
-- ===============================================================================================

CREATE OR REPLACE FUNCTION public.trigger_inherit_lineage()
RETURNS TRIGGER AS $$
BEGIN
    -- Automatically inherit school_id from creator's profile
    IF NEW.school_id IS NULL THEN
        NEW.school_id := (SELECT school_id FROM public.profiles WHERE id = auth.uid());
    END IF;
    
    -- If branch_id is missing and user is a Branch Admin, inherit it too
    IF NEW.branch_id IS NULL THEN
        NEW.branch_id := (SELECT branch_id FROM public.profiles WHERE id = auth.uid());
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMIT;
